### ISSUE TITLE
Fix the "Share and Cite" links in the CFDE Portal

### ISSUE THREAD

**Issue by dcfcjcheadle** [nih-cfde/cfde-deriva#100]
When navigating through the Chaise filter interface, the portal displays a 'Share and Cite' button to link to whatever content or filter setup you have.  This could be really useful, but the links don't currently work.

![image](https://user-images.githubusercontent.com/62721038/94847317-6f57ee00-03f0-11eb-813e-258f0aa5b674.png)

**Example:**
If I navigate to the following [page](https://app.nih-cfde.org/chaise/record/#1/CFDE:subject/RID=1-CBRP), I can click 'Share and Cite' to get a Versioned and Live Link:

- [Versioned Link](https://app.nih-cfde.org/id/1/1-CBRP@2V1-3VFW-CDJJ)
- [Live Link](https://app.nih-cfde.org/id/1/1-CBRP)

Unfortunately, following these links results in the page hanging and not ever getting to the site.

**Comment by karlcz** [comment]
@mikedarcy   Can you confirm that the `/id/` path is mapped in the reverse-proxy layer and that ermresolve is deployed?

**Comment by mikedarcy** [comment]
There was a configuration error in the current production system. It has been fixed.
