### ISSUE TITLE
Epic 1 warning banner

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#101]
@karlcz @victor73 @jrchudy 

Can we do something similar to this for the upcoming release? We have some DCCs that are ok with us using their data for this release, but not for the public-public until they've had a chance to update their model themselves. And they suggested we also mark the page to indicate that it's still in development/not finalized data

> One side note. Even though the development CFDE portal has not been advertised to the public or linked on NIH pages, it is already publicly accessible. It would be nice if you could add a warning banner stating that the data currently there is for development purposes only. We utilize such a mechanism for our test portals, e.g. http://mastertest.4dnucleome.org/.

**Comment by jrchudy** [comment]
@ACharbonneau we wont' be able to make this work entirely how 4d nucleome has it. This would require a change to the chaise stack to have the same exact banner notification. 

I can provide a CSS solution that will put a banner at the top of every page but won't be dismissible. It could look something like this:
![image](https://user-images.githubusercontent.com/2932600/97036651-ff371680-151c-11eb-881a-a04d312729fe.png)

**Comment by ACharbonneau** [comment]
Love it
