### ISSUE TITLE
Updated links for wireframes

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#102]
In Cia's wireframes there are some links to things where the links are not right. below are the corrected addresses:

------
1. 
![image](https://user-images.githubusercontent.com/1719360/97043173-1804f380-1540-11eb-9db6-6b46d3407a06.png)

should be to https://www.nih-cfde.org/
-------

2. 
![image](https://user-images.githubusercontent.com/1719360/97043343-569aae00-1540-11eb-8881-13252f246fd7.png)

should be to the sandboxed catalog that is shown in the summary. So something like "https://app-dev.nih-cfde.org/chaise/recordset/#15/CFDE:collection"

I know we don't actually have the internal machinery to actually tell the UI what the address is, and that's fine. 

-------
3. 

![image](https://user-images.githubusercontent.com/1719360/97043625-c27d1680-1540-11eb-9451-2457a8e1af0b.png)

this link should go to: support@cfde.atlassian.net

-------
4. 

I don't know if this was clear, but all of these links: 
![image](https://user-images.githubusercontent.com/1719360/97043822-11c34700-1541-11eb-8e33-5c47f878539d.png)

were meant to go to the sandboxed catalog, filtered to show that thing. Again, I know this won't actually work. Just clarifying.

**Comment by jrchudy** [comment]
#1 and #3 have been addressed. 
For #2, we need the finalized catalog before setting this (which catalog # are we going to use?)
For #4, those won't be links in the demo.
