### ISSUE TITLE
Refactor cfde-deriva API for pre-release catalog pipeline

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#112]
Like the new API for building review catalogs, add a separate API for building relelase catalogs

- [ ] Obtain release definition from registry
- [ ] Perform multi-datapackage load w/ appropriate policies
- [ ] Update registry with pre-release catalog URL
- [ ] Equivalent of submission ingest routine for multiple approved datapackages

**Comment by ACharbonneau** [comment]
Did this get resolved? Or should it get moved to epic 2 technical debt?

**Comment by karlcz** [comment]
@ACharbonneau  Sorry this is the issue I meant to comment on as something to do for March release. The initial version of this shouldl replace the previous epic 2 ad hoc release prep script.

**Comment by ACharbonneau** [comment]
I do not know how to test this. If someone tells me what to check, I will, but otherwise I will have to close it on faith.

**Comment by karlcz** [comment]
We should just close this. It's an internal implementation aspect
of the release tool and submission ingest system and is working as
expected.
