### ISSUE TITLE
identifier service - beta

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#12]

**Comment by mikedarcy** [comment]
The identifier service is available for beta testing of `minid` identifier minting. 

- The Python `minid` client software can be installed via Pip with `pip3 install minid`.
- Documentation for the `minid` client software is here: https://minid.readthedocs.io/en/read-the-docs/
- It is recommended to only mint minids in the **_test_** namespace for now. Use the `--test` flag with the `minid` client to do so.

Contact @mikedarcy or @NickolausDS for support.
