### ISSUE TITLE
Manual release tool

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#122]
Produce a minimum viable release tool (CLI) to work with registry. We will want to have a method to rebuild a release or cut a new one that properly complements the new submission pipeline.  This is needed to avoid a new operations hazard where the old manual method would not couple well with the registry, but also seems important to validate that the new registry design is sufficient to support a release discipline.

- [ ] A mode to "plan" a release, i.e. gather current latest approved submissions for each DCC into a release data structure in the registry
- [ ] A mode to "build" a release, i.e. construct a new catalog w/ all planned content (at a temporary pre-release catalog ID)
- [ ] A mode to "publish" a release, i.e. fiddle the lower-level ermrest registry to change the catalog ID.  (A stretch goal, could continue to do this manually in a pinch)

**Comment by karlcz** [comment]
@ACharbonneau  This is probably also something for March release.  This is complementary to the other issue #112 I just commented on, but to provide the CLI aspect I need around that API/library functionality.

**Comment by ACharbonneau** [comment]
I believe Karl said this was working, but I do not know how to test it. If someone tells me what to check, I will, but otherwise I will have to close it on faith.

**Comment by karlcz** [comment]
We should just close this.  It's what I used to prepare the
dev and staging replacement catalog "1" release preview data.
