### ISSUE TITLE
Specify epic2 navigation configuration changes

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#125]
With epic2 we need to revise our navbar structure(s) so they can be properly coordinated. We should also consider page and window title changes where applicable?  It seems like there are more page contexts to consider, and we may need some mode switching to provide more task-appropriate nav targets, but also some visual cue that you are in a different mode?

- [x] Some specific navbar options need to have ACLs defined alongside them to disable some of them in certain contexts and hide other options entirely. Started in [this PR](https://github.com/nih-cfde/cfde-deriva/pull/129).
- [x] Each submission needs its review page URL populated w/ appropriate plot page URL parameterized by the catalog ID
- [x] Static site, dashboard, and release catalog should share navbar config stored in release catalog
- [x] Per-submission summary (charts) page and review catalog should share navbar config stored in review catalog

| context | page title/info to disambiguate |
|---|---|
| static site | VPC ? |
| release content | VPC, tablename and/or record ID, "current release"? |
| dashboard of release content | VPC, sub-page, "current release"? |
| registry | VPC, tablename and/or record ID, "registry" or "submission system"? |
| review catalog | VPC, tablename and/or record ID, "submission in-review", DCC ID, submission ID, submission date? |
| dashboard of review content | VPC, sub-page + see previous? |

| context | nav target | current design/notes |
|---|---|---|
| static site | table in release | A drop-down list i.e. Browse... |
| static site | dashboard | A direct link i.e. Dashboard |
| static site | review content | A link to registry submission listing i.e. Data Review? |
| static site | registry admin | ? need multiple entry-point for CFDE-CC and DCC admins to do admin tasks? |
| release content | other tables in release | same Browse... drop-down? |
| release content | dashboard | same Dashboard link? |
| release content | review content | same Data Review link? |
| release content | registry admin | ? |
| dashboard |  tables in release | same Browse... drop-down? |
| dashboard | dashboard | currently links to self? |
| dashboard | review content | same Data Review link? |
| dashboard | registry admin | ? |
| review content | tables in release | do we need direct access to release tables? |
| review content | other tables in same review | need a variation on Browse... within same submission |
| review content | other review content | same Data Review link can escape from this submission? |
| review content | registry submission record | need quick access to approval/status of same submission |
| review content | registry admin | ? |
| registry | table in release | same Browse.. link? |
| registry | dashboard | same Dashboard link? |
| registry | review content | same Data Review link? |
| registry | other registry entry points | ? |

**Comment by ACharbonneau** [comment]
Are these pages already existing in dev so I could look at them? Or could you give me screenshots of what exists? That would help me with thinking about appropriate titles and navbar stuff

**Comment by karlcz** [comment]
Existing dev content examples would be:
1. The static site https://app-dev.nih-cfde.org/
2. The "release content" https://app-dev.nih-cfde.org/chaise/recordset/#1/CFDE:collection (from epic 1)
3. The registry of submitted datapackages https://app-dev.nih-cfde.org/chaise/recordset/#registry/CFDE:datapackage
4. An example "review content" https://app-dev.nih-cfde.org/chaise/recordset/#12/CFDE:collection (from epic 1)

NOTE:
- These dev navbars are not really coordinated yet, so don't expect to navigate among the bits of the dev site.
- The release catalog is the Epic 1 configuration and includes (broken) links to other epic 1 content
- You need to be logged in w/ appropriate group membership to see listings in the registry, but an anonymous view shows the overall page layout.
- If you do view the registry content, I think the links to submitted review content are broken, except for the oldest links to epic 1 content. I think this is due to the dev server auto-purging catalogs that are being built during submission tests...

**Comment by karlcz** [comment]
As a simplifying assumption, we are investigating how to get the navbar in each submission-specific "dcc_review" page (with charts) to load the same navbar config we have in the submission-specific chaise record/recordset pages.  Similarly, we think we can configure the static landing page and main dashboard to share the navbar config we will have in the "public release" catalog. Then, there would be three main navigation modes:
1. The standard _public_ navigation on static site, dashboard, and release catalog
2. The per-submission _review_ navigation on a specific review catalog and charts page
3. The _submission system_ navigation if you've found your way to the submission registry one way or another

**Comment by karlcz** [comment]
The latest ingest processing on app-dev also populates the review summary page URL to get to charts.

**Comment by karlcz** [comment]
The navbar ACLs have been updated on app-dev for some (but not all) contexts.  Others will depend on getting the code updated in the ingest service and affect future submission processing only.
- static site navbar (shared with dashboard and public release catalog)
- registry navbar (when viewing submssing list etc)
- prepared review catalog 189 https://app-dev.nih-cfde.org/chaise/recordset/#189/CFDE:file used to test pipeline code

The navbar in the review catalog is least important since the whole thing triggers a login dialog anyway. But, a careful observer can see that the navbar is locked during this error state.  Older catalogs do not have this config on dev.

The last remaining bit is to get the per-submission `dcc_review.html` page to obtain its navbar config from the corresponding catalog so that it will also have appropriate navigation options for the review task (including submission-specific links to browse the content or to get back to the submission or DCC pages in the registry).

**Comment by jrchudy** [comment]
https://github.com/nih-cfde/dashboard/pull/45 has been merged into the epic2 branch so the last bullet should be working now too:
>  Per-submission summary (charts) page and review catalog should share navbar config stored in review catalog
