### ISSUE TITLE
Optimize lingering slow queries for epic 2 plots

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#128]
It occurred to me that we should double-check whether the dashboard/reivew page and api service have any remaining dependency on slow ermrest queries, and weed them out by adding appropriate support in the pre-computed "stats" table and cfde-deriva dashboard query helper library, so we can swap to faster queries.

This will help avoid surprising latency/non-determinism with the plot UI when it is performing live queries on release data or new submissions which may have new performance issues...

**Comment by karlcz** [comment]
I believe we decided to postpone this until we see a need, and right now it seems the charts are working reasonably well even for non-cached visits by a new browser session.  Do we want the test team to make a final assessment of this?  Or should we just unlink this from the epic and leave it in the backlog for now...?  @ACharbonneau   @lliming

**Comment by ACharbonneau** [comment]
I'll see if anyone complains about slowness during testing, and if not it can go in the backlog.
