### ISSUE TITLE
Fix typo on registry page

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#131]
On the registry page:

https://app-dev.nih-cfde.org/chaise/recordset/#registry/CFDE:datapackage@sort(submission_time::desc::,RID)

The first facet search says "Submtting DCC" rather than "Submitting DCC"

**Comment by karlcz** [comment]
Fixed in code. This will be applied the next time I run a reconfiguration pass on the registries.

**Comment by ACharbonneau** [comment]
cool. Semi related question. For testing purposes, should little things like this all get a label or an epic or a something so we can easily find them later?

**Comment by karlcz** [comment]
This has been deployed to dev and staging.

I think it should be assigned to the epic if we consider it something that should be fixed before it is released...
