### ISSUE TITLE
Staging doesn't have all onboarded DCCs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#138]
In the onboarded DCCs list: https://app-staging.nih-cfde.org/chaise/recordset/#registry/CFDE:dcc@sort(RID) and registered groups: https://app-staging.nih-cfde.org/chaise/recordset/#registry/CFDE:group@sort(RID) there are only the 7 currently in the portal DCCs, and not all the ones that are supposed to be submitting data: https://github.com/nih-cfde/security/issues/8 

Need to add:
- [x] IDG
- [x] ExRNA
- [x] SPARC
- [x] HuBMAP

Instructions (WIP) https://hackmd.io/Z7dQ_ZTiQX2eDDB-0lMO6w

For automation:

- [x] Staging has all info
- [x] Karl extract them into the canned release data
- [x] Notified David/Nick to update Globus
- [x] Globus updated

**Comment by karlcz** [comment]
Should we call this not-a-bug as the manual onboarding sequence allows it to be fixed?  Or keep it around and have a followup task to capture the new DCC entries in the release that will be rolled to production later?

**Comment by ACharbonneau** [comment]
Can we leave it for the moment so I remember I need to onboard the rest? I want to make sure I've got IDG working before ti do the others.  I'll assign it to me

**Comment by karlcz** [comment]
Sure, maybe edit and add some checkbox [ ] TODO items...?

If we want to have these changes automatically incorporated into prod
(not another round of manual onboarding by you), then also add a
checkbox for you to signal when all values are present in staging and
a checkbox for me to extract them into the canned release data (and
keep me as an assignee too).

**Comment by ACharbonneau** [comment]
@DavidKelly999 @NickolausDS I added all the new dccs to Deriva in staging and linked them. I need you to run whatever update is needed in Globus to make them accept submissions.

@karlcz I'm not sure if you need to wait for Globus or not

**Comment by karlcz** [comment]
FWIW, the two post-onboarding steps are basically independent tasks:

1. update the automate+storage side to provision data storage locations
2. update the registry UI to unlock the navbar for the new DCC groups

the cfde-submit tool can be run as soon as (1) is complete, and direct
links to pages in the submission system will also work for the web UI,
but the "Data Review" navbar item will be locked until (2) is
completed.
