### ISSUE TITLE
Common Fund Program --> Show More Terminal Error

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#141]
This is a repeatable error. I think it's trying to display for all 506,150 results instead of knowing that there's only 7 programs?

In testing:

1. Browse all data by Biosample
2. In the Anatomy filter choose "All records with value"
3. In the Common Fund Program filter choose "Show more"

![image](https://user-images.githubusercontent.com/1719360/108378505-0e7c5700-71d3-11eb-924a-97e282963ceb.png)

If I skip step 2, the Common Fund Program filter has a "Show details" instead of "Show more", but "Show details" gives the same Terminal Error.

The Project facet also does this, however none of the others do, including ones with far, far more results than Program should have:

1. Browse all data by Biosample
2. In the Anatomy filter choose "All records with value"
3. In the Assay type choose "Show more":

![image](https://user-images.githubusercontent.com/1719360/108379417-e5a89180-71d3-11eb-9289-3368b360efa3.png)

1. Browse all data by Biosample
2. In the Anatomy filter choose "All records with value"
3. In the Described by File choose "Show more":

![image](https://user-images.githubusercontent.com/1719360/108383232-982e2380-71d7-11eb-94b2-bd56a15dab09.png)

**Comment by ACharbonneau** [comment]
Sorry, forgot to include we see this on both:

OS (including version): macOS Big Sur v11.2.1
Browser (including version): Safari v14.0.3

and 

OS (including version): macOS Big Sur v11.2.1
Browser (including version): Chrome  v88.0.4324.182

**Comment by karlcz** [comment]
This is actually  a "query runtime limit exceeded" error that is being masked by a Chrome-specific bug in Chaise that is turning it into a "Terminal Error".

I need to look and see if we can do something about the query complexity here.

**Comment by jrchudy** [comment]
The terminal error text is related to a bug that was found in chaise (technically ermrestJS) where some browsers weren't sending a status as part of the error response. We were relying on this status to be present and use that to map to an appropriate modal title. A change was merged yesterday to ermrestJS to resolve this.

https://github.com/informatics-isi-edu/ermrestjs/commit/c4e739da22c8b7b16a110c15ec0ef21937aced38

**Comment by karlcz** [comment]
The query timeout on staging has been adjusted from 15s to 55s. I don't see any easy cherry-picking optimizations we can do in this case, so am not sure to call this fixed or wontfix or...
