### ISSUE TITLE
Facet Panel runs off bottom of window and won't scroll

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#143]
Chrome version 88.0.4324.182
Mac OS BigSur 11.2.1

I'm in staging, posting a couple examples. It seems to happen on all pages. When I open one of of the upper facet options, it runs the lowest one half off my screen, and the panel won't scroll down any further:

![image](https://user-images.githubusercontent.com/1719360/108383814-1f7b9700-71d8-11eb-9829-b89dba8f8294.png)
![image](https://user-images.githubusercontent.com/1719360/108383978-489c2780-71d8-11eb-8a39-030d48f2a458.png)

changing window size doesn't seem to help:

![image](https://user-images.githubusercontent.com/1719360/108384048-5d78bb00-71d8-11eb-86e0-c78e51ace43e.png)

But if I can click the half box to open it, the scroll suddenly does allow me to scroll down further:
![image](https://user-images.githubusercontent.com/1719360/108384282-9add4880-71d8-11eb-9822-dfd806def25b.png)

when I collapse that bottom box, the scroll doesn't revert. It lets me scroll down to see the whole panel:

![image](https://user-images.githubusercontent.com/1719360/108384489-cb24e700-71d8-11eb-8a99-952d6d10a4fd.png)

But it does reset to the "won't scroll" version if I refresh or go to a new page. So I think it's an initial html setting?

**Comment by karlcz** [comment]
The facet panel is a separate scrollable region from the results. You have to do the appropriate action for your OS to send scroll events into that panel...  can you check that and confirm whether it is really broken or just not "discoverable"?

I know we have recurring battles where some browsers/platforms have decided to make scrollbars invisible (horizontal and vertical) which makes scroll capability hard to assume.  It even varies for some depending on what kind of pointing device(s) are detected by the browser (mouse vs touchpad vs touch screen)...  it's a constant annoyance to the web devs.

**Comment by ACharbonneau** [comment]
I'm not sure what you mean. On load, the facet panel scrolls, it just won't scroll far enough down. If I open the bottom facet options, that seems to reset the scroll length and allows me to scroll 100% of the way down. I can make a little video if that would help.

**Comment by karlcz** [comment]
@jrchudy   please take a look at this... Amanda is scrolling the sidebar but it is slightly truncated anyway.  I can partially reproduce on firefox too, though it seems to correct itself more easily with expansion of other facets.

**Comment by jrchudy** [comment]
Thank you for reporting this. This is a bug I experienced very sporadically while developing but couldn't understand how I produced it. It looks like it's a case with a long set of facets and not properly resizing the container to fit the contents. This will need to be fixed in https://github.com/informatics-isi-edu/chaise repository.

**Comment by jrchudy** [comment]
This has been fixed and the changes can be seen on app-dev. I'll update when staging has been updated for retesting.

**Comment by jrchudy** [comment]
This has been updated in staging and can be tested again.

**Comment by ACharbonneau** [comment]
Looks like it's fixed!
