### ISSUE TITLE
Sporadic terminal errors

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#149]
As I'm navigating around, I'm getting a lot of sporadic terminal errors. Following the same set of actions usually doesn't get me the error a second time, so it must be some kind of time out thing? Might be related to/already fixed by #141 

![image](https://user-images.githubusercontent.com/1719360/108548712-3abed300-72ba-11eb-950b-0148a55f328f.png)

**Comment by karlcz** [comment]
I think this was the chrome-specific chaise bug causing many errors to fall into terminal error, combined as you suggest with the other timeout issue.
