### ISSUE TITLE
How to navigate from "summary charts" to "registry"

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#151]
If I've navigated to the Summary Charts page for a submission, e.g. https://app-staging.nih-cfde.org/dcc_review.html?catalogId=33 the "Submission System" nav bar button becomes an "In Review Submission" button:

![image](https://user-images.githubusercontent.com/1719360/108557166-297bc380-72c6-11eb-8b32-e2a3d8474d2f.png)

Unfortunately, that means you loose all the navigation options that were in the "In Review Submission" button. 

I think this was to help with the "Where am I" navigation issue, but it makes it very unclear how to get back to the ["Submitted Datapackage"/registry page](https://app-staging.nih-cfde.org/chaise/recordset/#registry/CFDE:datapackage@sort(submission_time::desc::,RID)). 

This might be a good thing for the design team to look at/think about

**Comment by karlcz** [comment]
The second and third menu choices bring you back to the registry. The one "Submission ...UUID..." is a direct link to the submission's page in the registry.  The third item is the submitting DCC name and brings you to a list of all submissions for that DCC.  From there you can use all the submission system menu items and/or return to the review content.

I hadn't thought about how this looks in the charts page though.  The current design shares the same menu between the summary charts and the browsing review data.  We could add another link to go to the review content (the complement to the summary charts item)?

**Comment by karlcz** [comment]
Ha, actually I forgot the entire `Browse Submitted Data` menu on the left is for direct access to the content of the submission...

**Comment by karlcz** [comment]
I think we decided to park this for now and get user feedback on the Browse Submitted Data and In-Review Submission menus. Right @ACharbonneau ?

**Comment by karlcz** [comment]
One more thought is whether the In-Review Submission menu should have one more link that acts like Data Review but perhaps has a different label like "All Submissions"?

**Comment by ACharbonneau** [comment]
Yes, I think let's just park it and see what people say. We can reevaluate in a couple weeks after we have users

**Comment by ACharbonneau** [comment]
This actually got fixed when the dashboard team changed the link that used to go to the DCC homepage https://github.com/nih-cfde/dashboard/issues/47
