### ISSUE TITLE
Submission system dropdown reorder

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#154]
Karl mentioned he would do this at some point, but I'm making an issue anyway:

It would be nice if 'Submitted datapackages' was the first option in the dropdown since it's the default page:
![image](https://user-images.githubusercontent.com/1719360/108750579-32aba100-750f-11eb-8242-d0dc2dcec2db.png)

**Comment by karlcz** [comment]
I've done this in the code, and we'll see the change when we redeploy the environments this week.
