### ISSUE TITLE
Banner update for public release

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#163]
When the data goes public, we need to make the following changes to the banner at the top of the portal sites:

production: Should not have a banner at all
staging: "Staging Server. The data and features of this page are not official and are only for testing purposes."
dev: "Development Server. The data and features of this page are not official and are only for testing purposes."

I'm open to changing the specific language, but that's the gist.

**Comment by jrchudy** [comment]
Using the color suggestions from https://github.com/nih-cfde/dashboard/issues/42 from dashboard repo. 

Dev will use `#447e71` and staging will use `#7e4475` for the banner color .

**Comment by ACharbonneau** [comment]
banners in dev and staging look good. Should I leave this open for removing the one on production?

**Comment by jrchudy** [comment]
We should leave this open until production is updated. The changes for this rely on the build/install script choosing the right  CSS document to use as `custom.css`. When we build and deploy prod, we can then check if the recipe worked (banner is no longer there).

**Comment by ACharbonneau** [comment]
looks good
