### ISSUE TITLE
Portal analytics

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#164]
For all the other CFDE websites, we are using [Matomo](https://matomo.org/). It would be nice for me if I could have the same thing here, because I'm going to need to put together overall engagement reports with analytics from across all the sites, BUT just google analytics will work.

**Comment by RLC-DCPPC** [comment]
whether people are coming to it. Absolute minimum for end of March.

**Comment by RLC-DCPPC** [comment]
know stuff about our users.
List of stuff NIH would like to be able to know.

**Comment by ACharbonneau** [comment]
I have no idea how to test that this is done without making the site go live.

**Comment by jrchudy** [comment]
Same comment from me amanda. I don't know how to test this since we only want to gather analytics from production. I'm assuming I set everything up properly since it mimics what we have done for other deployments using deriva.

**Comment by ACharbonneau** [comment]
Analytics seem to be working. Google is tracking things
