### ISSUE TITLE
Remove 'testing' DCC data from production

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#167]
When we rebuild the catalog for the March release, we need to remove all the current data that we built for the demo. The release should include only approved submissions that DCCs have made themselves since 3/1/21

**Comment by karlcz** [comment]
I will probably need help determining which submissions to retain.  I see a few reasonable options:
1. Enumerate the submissions to retain here in issue description
2. Set a hard date where submissions are to be marked "approved" and retain only those marked as such
3. Identify a "latest submission to discard" if there is a clear moment where all subsequent submissions are to be retained

**Comment by ACharbonneau** [comment]
OK. 

- All DCC data that is showing in this page [https://app.nih-cfde.org/](https://app.nih-cfde.org/), right now needs to be removed. So, the currently public packages for: HMP, LINCS, KidsFirst, 4DN, GTEx, Metabolomics, and MoTrPAC
- I have told all the DCCs that they need to have submissions in by EOD today (3/17/21), and have something approved by EOD tomorrow (3/18/21). I did this assuming that we would have all manner of slightly late things, and that our for real cut off would be EOD Friday such that we can start testing and building the update on Monday (3/22).
- If, for example, HMP has not submitted and approved a package by EOD 3/19, then they will not have data in this first release. And that is fine. 4DN has already informed me that they're dropping out for this round. 
- Anything that is in the submission system, from a DCC, approved or not approved, should *stay*. We haven't announced or written a data retention policy, so I think we should just leave whatever they've put in until we have one.

**Comment by ACharbonneau** [comment]
Starting a list of ideas for data retention policy here: https://github.com/nih-cfde/training-and-engagement/issues/354

**Comment by karlcz** [comment]
I just want to confirm, are there any submissions on prod you would want removed?

If not, I think this issue has become redundant as it is really stating that our issue #179 will build a new release from all new submissions and not carry forward any of the legacy content we used to build prior releases.  That is implicitly how it will always work, so we're just declaring not to do any interim, hybrid release which mixes legacy and formal submissions.

**Comment by ACharbonneau** [comment]
> we're just declaring not to do any interim, hybrid release which mixes legacy and formal submissions.

This is true. So I think yes, this can close/is redundant
