### ISSUE TITLE
Profiles catalog module

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#168]
For profile and personalized dashboard support, we need to add a profiles catalog module for holding the model definition and deploying the new storage space.

**Comment by jrchudy** [comment]
Converting this issue to an Epic to track the process for deploying.

**Comment by karlcz** [comment]
This has been in app-dev's registry for quite a while, but we expect to drop and recreate the `saved_query` table soon to modify its defintion based on recent engineering meetings.

**Comment by karlcz** [comment]
WIth the saved_query.encoded_facets column deployed to app-dev, I am moving this to the QA column, but it's for the other devs doing integration to give test feedback.  I don't think there's an end-to-end UX to test with a user persona hat on yet...
