### ISSUE TITLE
portal - deploy to production

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#17]
Start: 6/1/20
End: 9/20/20

Deliverable was: nih-cfde/deliverables#111 however the public release was delayed to 9/30/20

**Comment by karlcz** [comment]
is this a stale thing we should close?

**Comment by ACharbonneau** [comment]
It's still open because https://github.com/nih-cfde/dashboard/issues/6 is attached to it, and that's still open. We should probably unattach it, and also move it to the backlog unless someone is really working on it
