### ISSUE TITLE
Deploy 2021Q1 portal to staging

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#171]
Release to staging checklist (in order they should be performed):

- [x] Reprovision staging RDS instance as needed to QA our planned prod config (Mike D.)
- [x] Deploy tagged deriva web service stack in catalog-staging instances  (Mike D.)
- [x] ~Do ermrest-deploy for schema upgrades of ermrest service (Karl, Mike D.)~ (_this happened during scaling tests in july_)
- [x] Upgrade registry catalog via `python -m cfde_deriva.registry app-staging.nih-cfde.org reprovision registry` (Karl)
- [x] Manually adjust `ermrest` DB to restore original catalog ID for current release and bind alias "1" to it (Karl)
- [x] Deploy tagged stack in staging action provider (David)
- [ ] Resubmit DCC packages to staging via tagged `cfde-submit` CLI  (Amanda, Karl)
- [ ] Plan "release" catalog via `python -m cfde_deriva.release draft` (Karl)
- [x] Expunge existing "content-ready" review catalogs, changing state to "obsoleted" or "submitted" as appropriate (Karl)
- [x] Deploy tagged dashboard-api, chaise, dashboard, etc. to app-staging (Mike D., Josh)
- [ ] Build "release" catalog via `python -m cfde_deriva.release build` (Karl)
- [ ] Move alias "1" to new release via `python -m cfde_deriva.release publish ...` (Karl)
- [ ] Rebuild review catalogs via `python -m cfde_deriva.submission build ...` as appropriate (Karl)

Testing thoughts:

We know data can be submitted to prod, so we do not need to run cfde-submit tests prior to upgrading staging services. Running it after will help test that the new submission flow will work in Q2. (New registry, new action provider, new CLI.)

The deployment will have some phases with broken dependencies:
- old dashboard-api + dashboard can only view old release or old review catalogs
- new dashboard-api + dashboard can only view new rlease or new review catalogs

To break this into async pieces:
- we deploy the registry and action provider first, so we can test the new submision path while loading new data we need for a full release test
- we can prepare the new release catalog ahead of time, knowing its dashboard won't work yet, but chaise browsing will work, and it is available at an alternate catalog ID
- we can drop existing review catalogs that will be incompatible with the new dashboard
- we can quickly "publish" the new release by swapping the special catalog alias "1" in concert w/ UI and service upgrade
- we can later rebuild some review catalogs for older submissions to make them compatible with the new dashboard, if desired

**Comment by karlcz** [comment]
I've repurposed this staging deployment issue into a more complete checklist we can use to coordinate...
