### ISSUE TITLE
Who is updating 'decision pending by CFDE-CC'?

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#176]
I've been assuming this is @karlcz but maybe it's me? Or Arthur? Or Mike? Is this a 'technical' sign off that it just didn't break anything? Or a "someone has looked at this and decided it seems minimally scientifically sane" sign off?

**Comment by karlcz** [comment]
It sounds like we need a CFDE-CC approval policy :-) But my
expectation was that it might address both concerns you raise.

1. CFDE-CC bioinformatician/scientific review as the long-term purpose
   of review.  This includes vocabulary usage/extension but probably
   ought to include more holistic review of C2M2 usage?

2. Human QA/validation to cover gaps we know about in our automated
   validation (e.g. our lack of enforced identifier hygiene) or
   other gaps we might find in the integration.

The "content approved" decision should be for submissions we believe
are ready to relase with the current production system.

The "content rejected" is when (1) or (2) finds problems with the
submission which we believe should be resolved by revision and
resubmission of the DCC's inventory.

I included the "content approved but held" approval state with the
idea that we might need it for workflow management in this phase, when
identifying issues in (2) where we think the appropriate solution is
to get an engineering patch release before we can include the
submitted data into a public release.

**Comment by ACharbonneau** [comment]
Do DCCs get notified when we change their approval status? I just tried approving one of my test ones and didn't get anything so I'm assuming no?

**Comment by karlcz** [comment]
No, there isn't any notification.  I'm not even sure what that would
mean... are you thinking email to the primary dcc contact info
in the submission?  Or something more aware of the DCC groups and/or
submitting user?

**Comment by ACharbonneau** [comment]
I'll make an issue about it as a feature request where I actually think about what it would look like, at the moment, a DCC just asked me if they would be notified and I didn't know the answer :)
