### ISSUE TITLE
Build public release catalog

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#179]
We need to rebuild the public catalog with DCC submitted content.

- [x] Identify release constituent submissions  (see detailed sub-tasks below)
- [x] Build new release candidate catalog
- [x] Switch it into place as catalog "1"

## Get DCC and CFDE-CC approved submissions

- [x] HMP
- [x] HuBMAP
- [x] LINCS
- [x] GTEx
- [x] Kids First
- [ ] ~SPARC~
- [ ] ~IDG~
- [x] Metabolomics
- [x] ExRNA

## Make sure they supply the newly required dcc_primary_contact.dcc_abbreviation

- [x] HMP
- [x] HuBMAP
- [x] LINCS
- [x] GTEx
- [x] Kids First
- [ ] ~SPARC~
- [ ] ~IDG~
- [x] Metabolomics
- [x] ExRNA

**Comment by ACharbonneau** [comment]
DCCs and whether we expect them to submit data:

- 4DN: No
- MoTrPAC: No
- HMP: Yes. Submitted and Approved
- HuBMAP: Yes, gave extension, expect Thursday
- LINCS: Yes. Submitted and Approved
- GTEx: Yes. Submitted and Approved
- Kids First: Yes
- SPARC: 
- IDG: Yes
- Metabolomics: Yes
- ExRNA: Yes

**Comment by karlcz** [comment]
@ACharbonneau   please see new checklists in issue summary.  Given the late change to the dcc_primary_contact table, I think we should make this an explicit check rather than assume the approval decisions were checking this detail...

**Comment by ACharbonneau** [comment]
Thats fine. I don't know how to check it without downloading all the bags tho. Is there a way to view that table in the portal?

**Comment by karlcz** [comment]
If the submissions prepared successfully to allow review, you can view
the table contents via chaise, but I guess we don't provide
navigation to the DCC Primary Contact table right now. :-/

Here's the clumsy workaround:

1. Follow "browse data" link for a submission in registry
2. Notice you are on the "file" table in the browser location URL
3. Edit the browser location from "file" to "primary_dcc_contact"

E.g. this is the initial browsing URL for a recent submission,
followed by the edited URL to see the dcc contact table instead:

***@***.***(RID)

***@***.***(RID)

**Comment by ACharbonneau** [comment]
I checked them all for abbreviations. They're set.

**Comment by karlcz** [comment]
I have tested the release tool on app-dev so I think we're set to cook staging or prod releases when ready.

**Comment by ACharbonneau** [comment]
I should have them all in staging by lunch today (monday)

**Comment by karlcz** [comment]
The release candidate is built at a temporary location https://app.nih-cfde.org/chaise/recordset/#118/CFDE:file
