### ISSUE TITLE
Level 1 statistics in Related Table section of Assay Type record

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#183]
Today in the UX meeting @abradyIGS noticed that a "Level 1 Statistics" table was still being shown to the users if they navigate to the record page for an individual Assay Type. The link below on staging shows 12 records in that related table:

https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:assay_type/RID=1-AJEP

**Comment by karlcz** [comment]
Right, the vocabs need explicit configs to avoid the heuristic
config exposing these backend details...

**Comment by karlcz** [comment]
We went through this together on app-dev catalog 1 and think it looks good.  I'm also applying the same change to the (many) app-dev review catalogs to minimize confusion.
