### ISSUE TITLE
Add globus storage to chaise internalHosts config

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#186]
We should try setting the chaise-config `internalHosts` field to a list of hostnames including the globus storage where we hold submitted datapackages.  It's probably OK to just share one list across all VPCs rather than making VPC-specific lists

- prod: g-882990.aa98d.08cc.data.globus.org
- staging: g-3368fe.c0aba.03c0.data.globus.org
- dev: g-c7e94.f19a4.5898.data.globus.org

**Comment by karlcz** [comment]
I think we should probably do this as part of current release epic?

**Comment by ACharbonneau** [comment]
I do not know how to test this. If someone tells me what to check, I will, but otherwise I will have to close it on faith.

**Comment by karlcz** [comment]
You can close it, but a quick check would be: go to the submission
system list of submissions and see links to the prepared catalogs and
raw bdbags, they should all appear as normal intra-site links.  Also,
cllicking such a link should take you straight to the resource,
without a Chaise interstitial modal telling you that you are leaving
the site.

It's categorical, so you only need to consider one link of
each type. There's no need to check many rows by hand.
