### ISSUE TITLE
A group with "admin" role for a DCC gets forbidden error when submitting

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#187]
It seems the ingest process requires the client to belong to a group with "submitter" role and does not consider a group with "admin" role to be sufficient.  This looks like an oversight in testing of the authorization check, due to not having previously enrolled any DCC admin groups.

**Comment by karlcz** [comment]
This is fixed in the userprefs branch but cannot be tested until it is redeployed on the action provider.

**Comment by jrchudy** [comment]
@karlcz now that we have updated dev/staging/production for the September release, can this be tested now?
