### ISSUE TITLE
tool tips should not have model levels 

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#190]
we dropped the level 0/level 1 nomenclature, but the tool tips still say 'level 1' in several places:

![image](https://user-images.githubusercontent.com/1719360/112900887-0bb63100-90b2-11eb-9c2f-02d378996add.png)

![image](https://user-images.githubusercontent.com/1719360/112900951-24264b80-90b2-11eb-808a-7eac00e26e81.png)

**Comment by karlcz** [comment]
This is reconfigured on app-dev catalog 1 and reconfiguration of existing submissions is in progress.
