### ISSUE TITLE
drop 'synonyms' from facets and tables

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#191]
we dropped synonyms from the controlled vocabulary tables in the model, but they're still showing up as facets and as columns:

![image](https://user-images.githubusercontent.com/1719360/112901104-533cbd00-90b2-11eb-9969-09577aded259.png)

**Comment by karlcz** [comment]
This is done to app-dev catalog 1 and reconfiguration of existing dev submissions is under way...

**Comment by ACharbonneau** [comment]
bringing back synonyms anyway. closing
