### ISSUE TITLE
Improve diagnostics to include table(s)

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#195]
This is from an IDG submission that came in today: 2021-03-30 10:38:45 (ID 9fc66e24-9165-11eb-8e7d-b37da3bc8f6e)

the diagnostics say:

> Found 4 errors in datapackage "datapackage.json". First error: There is an extra label "" in header at position "4"

Which he interpreted as "I need to edit the JSON file" when really the error is that he had synonyms columns in  assay_type.tsv, anatomy.tsv, taxonomy.tsv, and data_type.tsv files 

It would be much easier for users to diagnose their issues if it included the table names

link to bug report: https://github.com/nih-cfde/published-documentation/discussions/223#discussioncomment-549391

**Comment by ACharbonneau** [comment]
FYI I also get this same message from the tool/in an email when I tried to submit the same bad bag. 
![image](https://user-images.githubusercontent.com/1719360/113180171-6bc9e600-921e-11eb-8eca-bdc5ff6694b4.png)

not sure if that means this is also an issue that needs to be fixed in cfde-submit or if the tool just gets messages passed to it from the portal

**Comment by karlcz** [comment]
This error info comes from the frictionless validation report, so we'll have to look into this more and see if the report offers additional file metadata whioh we might be accidentally ignoring...
