### ISSUE TITLE
Reorder, rename, and remove columns from recordset and record

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#196]
In the UX meeting today, @owhite brought to our attention that some of the columns visible on recordset for some tables should be reordered, renamed, or removed entirely. Linked document detailing suggested changes:
https://docs.google.com/document/d/1yxgYhmOH3ZuuE7XwWWrtAX9Sjc7J7ScUDSDBUGavXxw/

One thing to keep in mind is how this content is reflected in export. Should columns in export be renamed accordingly as well?

**Comment by karlcz** [comment]
I think export should try to align to the C2M2 model and so expose its actual column names (and table structures) for programmatic access by someone who is reading the C2M2 specification.

I don't know if we want to offer multiple export modes, i.e. another targeting a naive user who is using the web UI and not learning about C2M2?  This is a trade off to allow some easier, casual access but at risk of creating a sub-community with less engagement with our metadata federation efforts and its own separate support requirements...

**Comment by ACharbonneau** [comment]
I would not expect any of our users to look at the C2M2, or even know it exists unless they are super users. Our target end user demographic is "clinical scientists looking for data". The only people who know/care about the model are us and the DCCs that need to build manifests.

**Comment by ACharbonneau** [comment]
Owen and I went through the new catalog that has Karls performance updates and made a new shortlist of changes. Text below is the desired new column view, in order:

File:

View | Common Fund Program |  Project | File Format | Data Type | Assay Type | Size In Bytes | Filename | Persistent ID | Creation Time

Biosample:

View | Common Fund Program | Project | Anatomy | Assay Type | Local Id | Persistent ID | Creation Time

Subject:

View | Common Fund Program | Project | Taxonomy | Granularity | Local Id | Persistent ID | Creation Time

Collection:

View | Name | Description | Creation Time

Project:

View | Common Fund Program | Name | Description | Creation Time

Additionally, on the Project page, we'd like the mouseover text for the Project title to be:

`An administrative subdivision of DCC activities typically associated with a research grant.`

Note, we know that adding Common Fund Program to the tables might be untenably slow. We'd like to try it in testing and see how it performs

**Comment by karlcz** [comment]
All of these have been applied to app-dev catalog 1.  I deviated on collection to add Common Fund Program and Project columns first, to be consistent with the other three C2M2 entities.
