### ISSUE TITLE
Ingest adds stable dcc id info to portal catalogs

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#198]
For epic 3, we need to handle new dcc info in the submission ingest and release builds.
- [x] Adjust portal model to include a `dcc` table (derived from registry table of same name)
- [ ] ~Revise Chaise hints to use `dcc` table for DCC/common fund program facet filtering~ N/A
- [x] Revise navbar menu to browse to `dcc` table instead of `primary_dcc_contact`
- [x] Allow for `dcc` content to arrive in future submissions (anticipating Arthur/modeling team will approve C2M2 change)
- [x] Devise a transitional method to populate `dcc` from older submissions... fusion of `dcc_primary_contact` and ingest process knowledge.
- [x] Populate `dcc` info during review catalog builds (ingest flow)
- [x] Populate `dcc` info during release catalog builds (manual release flow)

**Comment by karlcz** [comment]
After further review, the previous `primary_dcc_contact` table wasn't really used by the facets so there isn't anything to translate yet.  There is a navbar entry to replace.
