### ISSUE TITLE
deploy stable dcc id changes to dev

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#199]
Once we have the new `dcc` table feature in the portal catalog building processes:

- [x] Manually validate cfde-deriva feature with simulated submissions
- [x] Deploy cfde-deriva feature to action provider
- [x] Resubmit and "approve" existing release content for each DCC into dev
- [x] Rebuild dev's release catalog with new feature

**Comment by karlcz** [comment]
I think this issue status is stale, the actual work was done and has been in app-dev for quite a while
