### ISSUE TITLE
Changes to user profile model for saving personal dashboard configuration

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#206]
Currently we discussed adding a jsonb (I think we said `jsonb`) column to the profile model to save the configuration of the personalized dashboard page. This includes the selected graph from the carousel, selected DCCs for the graph widget and the axis options that were selected. Maybe this json configuration also includes the state of the favorites widget too?

Feel free to list more options that we want to add to the user profile model for configuration purposes.

**Comment by karlcz** [comment]
Can someone verify that this would be sufficient?
- Add `dashboard_config` of type `jsonb` in the `user_profile` record

The jsonb type is a database type that stores the validated and parsed JSON structure. It is not verbatim JSON text, and so does not preserve document ordering of object keys nor allow object keys to appear more than once.  But, it will preserve the content of each field and of course will preserve docment order for arrays stored in any fields.

**Comment by karlcz** [comment]
I've deployed a column `dashboard_state` that takes JSON in the `CFDE`.`user_profile` table in app-dev's registry.  It should be accessible only to the profile owner (or administrators of the registry).
