### ISSUE TITLE
Item Not Found Schema Error

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#207]
I can consistently create this error by:

1. [Open submission system ](https://app.nih-cfde.org/chaise/recordset/#registry/CFDE:datapackage@sort(submission_time::desc::,RID))
2. View details for any data package
3. In 'Browse All Data' dropdown in the header bar, choose any view. Here I chose biosample:

![image](https://user-images.githubusercontent.com/1719360/121709896-05c3cf80-caa7-11eb-8a54-753993d0d95d.png)

**Comment by karlcz** [comment]
Hmm, this seems like a weird policy corner case.  You are able to see the submission system listings but do not have permission to see the content of the review catalogs!  I will check with you out-of-band to get a list of your groups for that particular login identity (don't share them all here).

**Comment by karlcz** [comment]
This was fixed in app-dev and will be corrected in prod with the next release...
