### ISSUE TITLE
deployment and ops management of portal stack (AWS)

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#21]
Start: 4/1/20
End: 7/1/20

**Comment by mikedarcy** [comment]
I've attached a spreadsheet with some preliminary AWS estimates for min/max spec and upfront/no-upfront pricing using reserved instances. [CFDE_AWS_Estimates.xlsx](https://github.com/nih-cfde/cfde-deriva/files/4405858/CFDE_AWS_Estimates.xlsx)

**Comment by ACharbonneau** [comment]
Infrastructure
