### ISSUE TITLE
Add Saved Query and Favorites annotations

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#214]
To annotate tables to show the saved query UI features, the following should be applied to the display annotation on the catalog, schema, or table. 
```JSON
"tag:misd.isi.edu,2015:display": {
  "show_saved_query": true
}
```

If defined on the catalog, all tables in all schemas will use the value. Anything defined on a schema or table will override its parent model element's annotation definition. This is described better in the [annotation documentation](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2015-display).

To annotate a table that has favorites saved for it, the following annotation should be added to the table-config annotation on the table.
```JSON
"tag:isrd.isi.edu,2021:table-config": {
  "user_favorites": {
    "storage_table": {
      "catalog": "1",
      "schema": "table_config",
      "table": "my_favorites"
    }
  }
}
```

If any of the values are missing or the values used to create the ermrestPath are not strings (catalog should be a string value), the favoritesPath will be set to null and the favorites feature turned off.

_annotation.md documentation pending for table-config..._

**Comment by karlcz** [comment]
What is the rest of the config for the saved query interface?  I want to explicitly configure the storage catalog, schema, table in the same place rather than let them be scattered in different artifacts...

**Comment by karlcz** [comment]
And doesn't the storage-table config need a config to indicate the key mapping?  e.g. 

```
"user_favorites":` {
   "key_col": "id",
   {
      "catalog": "registry",
      "schema": "CFDE",
      "table": "favorite_assay_type",
      "foreign_key_col": "assay_type",
      "user_id_col": "user_id"
   }
 }
```
to tell it that we're saving the `id` key into the `assay_type` foreign key of the association and the authentication client ID into the `user_id` foreign key?

**Comment by RFSH** [comment]
Other annotation changes are,

1. To disable "default csv export option", you just need to add an empty `visible-columns` list for `export` context:
  
    ```json
    "tag:isrd.isi.edu,2016:visible-columns": {
      "export": []
    }
    ```

2. To define a key mapping for facets, you need to define `stable_key` or `stable_key_columns` to `table-config` annotation (I haven't pushed the changes for this yet.)

    ```json
    "tag:isrd.isi.edu,2021:table-config": {
      "stable_key": ["schema", "constraint"]
    }
    ```

**Comment by jrchudy** [comment]
Change to the chaise-config annotation set on catalogs for saved queries and terms and conditions requirement for login:
```
"tag:isrd.isi.edu,2019:chaise-config": {
  savedQueryConfig: {
    storageTable: {
      catalog: "registry",
      schema: "CFDE",
      table: "saved_query"
    }
  },
  termsAndConditionsConfig: {
    groupId: "https://auth.globus.org/96a2546e-fa0f-11eb-be15-b7f12332d0e5",
    joinUrl: "https://app.globus.org/groups/96a2546e-fa0f-11eb-be15-b7f12332d0e5/join",
    groupName: "NIH CFDE Portal Members"
  }
}
```

**Comment by karlcz** [comment]
A first version of this is applied to app-dev catalogs 1, registry, and 397 (a submission review catalog)

**Comment by karlcz** [comment]
This was applied to the other existing review catalogs as well.  But, until the action provider is updated, new test submissions might appear with the older config.
