### ISSUE TITLE
Nav bar is greying out My Dashboard after it's been clicked

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#216]
![image](https://user-images.githubusercontent.com/1719360/130818050-a2189fd6-c595-42f3-95e9-accd22cc975a.png)

If you:

- go to the homepage:  https://app-staging.nih-cfde.org/
- click My Dashboard
it opens a new tab for My Dashboard.
- on the original tab, that is still the homepage, the 'My Dashboard' link in the nav bar will now be greyed out. It stays greyed out until/unless you reload the page

I think the css must be set to grey on click but it isn't recovering? It's very weird, and makes it look like you can no longer access the My Dashboard once you've gone there once.

**Comment by karlcz** [comment]
I can reproduce this as well. It behaves the same way whether anonymous or logged in when you click.

A related question, do we want this link (and others) still opening in a new tab or rather navigating the current tab?

**Comment by jrchudy** [comment]
> This seems to be a general bootstrap CSS issue that affects all our buttons and menus. The focus leaves the button during the click event and leaves it in an activated style. Clicking elsewhere in the window resets to default state.

This is exactly the issue. Since we were opening in a new tab, the focus would stay on the last clicked spot on the page.

We could change the other navbar menu options (that link outside of deriva) to open in a new tab. Looks like every link in the navbar opens in the same tab currently.

**Comment by jrchudy** [comment]
The plan is to change this behavior to only grey the option happen "on hover" and remove/override the rule for "focused".

**Comment by karlcz** [comment]
I wonder, does this have accessibility implications?

is this styling the only way someone can see the control state if
using keyboard navigation, for example?

**Comment by jrchudy** [comment]
Looks like this was occurring because of a style I added to the `custom.css` that is being deployed to override other styles from the dashboard and chaise. There was no reason for me to override it in the first place, so I don't think it has any accessibility implications.
