### ISSUE TITLE
Stale favorites status can be seen in facet sidebar when other actions change the favorites status for a term

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#228]
## actual

The anatomy and anatomy slim facets both conenct to the same anatomy vocabulary. When a term is favorited, it is favorited regardless of path to reach the vocabulary.  But, the UI can show stale status known at the time a UI element was rendered, and not update to show state changes caused by other UI events independent of that UI element.

## original

For Anatomy we have both an Anatomy facet and an Anatomy Slim facet. Because of the way slimming works, some terms appear in both facets (digestive system, immune system, etc).

If I favorite 'immune system' in one of those facets, it does not automatically favorite it in the other facet. The implication to the user is that the 'Anatomy' immune system is not the same object as the 'Anatomy (Slim)' immune system. 

But, they are exactly the same. I've toggled them back and forth and favoriting from either facet correctly gives me a dashboard link to the one and only ['immune system' page](https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:anatomy/nid=356) 

So the behavior of the favoriting is correct, this is just an issue of the two related facets displaying conflicting information/not acting like they're related

**Comment by karlcz** [comment]
Fixes are in staging. The facets will reload asynchronously when "dirtied" by interaction with the favorites star icons.
