### ISSUE TITLE
Opening the Show More box removes star visual from selected facets

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#229]
This was previously Example 1 in #218 but I think I have the problem down to its base malfunction now:

If you:

1. have a term selected in a facet (any term, any facet with favoriting)
2. select "Show More" for that facet
3.  Click "Submit" in the Show More popup (it doesn't matter if you make more selections or not)
4. the stars next to the terms that were selected in step 1 will now be disappeared. They don't get unselected, and they maintain whatever their favorite status was, but they disappear
5. The only way to reappear them is to refresh the page

Example:

https://user-images.githubusercontent.com/1719360/131009347-4abc5e92-d4d6-4b6b-931c-eb9f39c9da64.mov

Other Notes:

- This does not happen cross-facet. So, selected Assay types don't lose their star visualization if I open Show More in Anatomy. 
- This does not happen if you "cancel" the Show More box instead of "Submit"ing
- For long name assays, when the star disappears it lets the name be longer. So if your selected term is "real time polymerase chain reactio..." when you lose the star it becomes "real time polymerase chain reaction as..." I think that means that the star is really disappearing, and it isn't just a css or display thing, the text thinks there is real empty space there.

**Comment by karlcz** [comment]
A fix for this is also in staging, addressing certain loss of UI state when the "Show More" facet modal is dismissed by the submit button.
