### ISSUE TITLE
Add new help links

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#232]
Add these under 'User Help' in the nav bar:

- Submit a feature request or bug report: <https://github.com/nih-cfde/published-documentation/discussions>
- Email the helpdesk: <support@cfde.atlassian.net>. this should be a mail-to

Gathered from other discussion:
- Privacy Policy: <https://docs.nih-cfde.org/en/latest/about/privacy/>

**Comment by karlcz** [comment]
what position should they go in, relative to the existing items:
1. Portal User Guide
2. Cohort Building Tutorial
3. About the CFDE

**Comment by ACharbonneau** [comment]
Sure!

**Comment by karlcz** [comment]
I made these Title Case to be consistent with the rest of the menu, and put them on the app-dev landing page.
