### ISSUE TITLE
Browsing UX punch-list 2021Q2

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#237]
We need to triage the UX review reports and revise the C2M2-based data browsing catalog UI hints...

No known issues as of 2021-09-28, but let's add small nits here if any are found during testing in coming weeks.

**Comment by jrchudy** [comment]
From the UX meeting this morning, we discussed the new facets that will be available:
 - file.compression_format
 - subject.{[sex, race, ethnicity](https://osf.io/qjrnp/), age_at_enrollment}

And the [new model features](https://osf.io/29cde/):
 - gene (CV) entity
    - + biosample_gene association
 - substance & compound (CV) entities
    - + subject_substance association
    - + biosample_substance association

**Comment by karlcz** [comment]
those extensions are covered by another existing issue for the 2021Q2 C2M2 extensions in the portal #244
