### ISSUE TITLE
Changes to the approval statuses

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#239]
NOTE: this is in progress and under discussion, but the original notes below are pretty stale and do not accurately reflect the planned changes.

## 2021Q2 plan

as per wireframes, the datapackage (submission) listings will get separate fields for different aspects of state and these will expose the actual state values from the submission system:
- ingest status: actual datapackage status, mostly about automatic ingest processing/validation
- dcc approval: data-entry fielld for human reviewer/approver
- release status: a bit of a hack, the heuristically most-relevant state from all releases linked to the package

These fields continue to draw from separate vocabulary tables specific to their concept spaces. These values are what will get assigned some color/icon decoration to help with visual scanning of the submission listings, but each submission will have (up to) 3 such decorations, not a single fused status indicator.

- [x] drop the “cfde_registry_decision:approved-hold" status. Any existing references will be rewritten to regular approved state during upgrade.
- [x] split out the separate fields above as per wireframe
- [x] hide `id` column from foreign key pop-ups for status values
- [x] release tool should change older release to "obsolete" when publishing new release
- [x] release tool should change older submissions to "obsolete" when a newer approved submission is incorporated into a (draft) release?
- [x] specify how Amanda or other admins can easily use release tool to curate a next-release advertisement which will improve the UX for release status in above items...

### Ingest Status aka datapackage.status

A fully successful package goes through these states (with noted caveats):
1. submitted
2. bag-valid
3. check-valid
4. content-ready (end of automatic ingest)
5. release-pending (in original design, but currently ignored)
6. obsoleted (after a newer submission is approved and detected for same DCC)

Other terminal states can be reached to abort the normal flow:
- bag-error
- check-error
- content-error

### DCC Approval Status

A successful packag goes through:
1. pending (a decision has not been entered)
2. approved

Or the alternate decision exits to:
- rejected

### Release Status

A fully successful release goes through these states (with noted caveats):
1. planning (set of consituents can still be changed)
2. pending (constituents frozen, processing MAY be under way)
3. content-ready (content can be previewed and/or published)
4. public-release (will be set by latest release tool)
5. obsoleted (has been replaced by newer release)

Other terminal states can be reached to abort the normal flow:
- content-error
- ops-error
- rejected

### Submission Release Status

A submission may be connected to more than one release. To make a useful UX, we have to start managing a "next-release" in the `planning` state during a quarter, so it can reflect our nominal plans for the next release and provide useful tracking of each DCC's latest approved submissions.

Then, we can gather all release states connected to a submission and prioritize them to choose a most-relevant state as the overall release status to indicate for a submission. Here is the prioritzed order of the current prototype under development:
1. public-release (i.e. data is currently visible in public release)
2. planning / pending  / content-ready (i.e. data is currently part of "next-release")
3. obsoleted (i.e. was previously released but now superceded)
3. failed / rejected / ops-error (i.e. data is part of a failed release plan)

Generally, a submission will start in a fourth quasi-state, having no connection to a release and hence no release status at all. 

## original notes

Below is a list the changes specifically for the approval statuses listed under the "Submission Page" [heading](https://docs.google.com/document/d/1tYtBXL3HmxSbyA8lVwCvXQKQI6xssoL3pur65RyRxoY/edit#heading=h.elnhjoh6v9uv).
### Changes to status table data:
 - Remove ID column from approval table in foreign key popup
 - Drop the “cfde_registry_decision:approved-hold" status
 - "CFDE approval [Status?]" with “Package Release Status”
   - clarify what this means
     - column display name in recordedit?
     - table display name in foreign key popup?
     - image under "Approval Popup" in [word doc](https://docs.google.com/document/d/1tYtBXL3HmxSbyA8lVwCvXQKQI6xssoL3pur65RyRxoY/edit#heading=h.ee2eylu0jw78) shows "Status" instead
 - `cfde_package_rel_status:pending` (is this `cfde_registry_decision:pending`?)
   - name: "decision pending" -> "pending"
   - description: "An approval decision is due, pending content review." -> "The most recent DCC approved package will proceed to processing at the next submission cutoff date."
 - `cfde_package_rel_status:content-ready` (is this now `cfde_registry_dp_status:content-ready`?)
   - name: "content ready for review" -> "content ready"
   - description: "Submission is loaded and ready for human review." -> "This package is loaded for inclusion in the upcoming release."
 - `cfde_package_rel_status:content-error` (is this `cfde_registry_dp_status:content-error`?)
   - name: "failed (content error)" -> "content error"
   - description: "Content loading has failed, submission cannot be processed." -> "An unexpected error has occurred during loading, the CFDE-CC will contact you for assistance."
 - `cfde_package_rel_status:rejected` (is this `cfde_registry_dp_status:rejected`?)
   - name: no change
   - description: "Submission has been rejected by human reviewers and should not be included in subsequent releases." -> "This package could not be included in the upcoming release."
 -  `cfde_package_rel_status:public-release` (is this `cfde_registry_dp_status:release-pending`?)
   - name: "release pending" -> "public release"
   - description: "Submission has been approved and should be included in subsequent releases until obsoleted." -> "This package is visible in the current public release."
 -  `cfde_package_rel_status:obsoleted` (is this `cfde_registry_dp_status:obsoleted`?)
   - name: no change
   - description: "Submission has been obsoleted by a more recently approved submission from the same DCC." -> "This package has been replaced by a newer one in the public release."

**Comment by karlcz** [comment]
I've modifed the relase tool so that it is easier to use for recurring curation of the "next relelase" draft, just by running the `draft` sub-command as in:

`DERIVA_SERVERNAME=...  python3 -m cfde_deriva.release draft`

this will idempotently create or find and reuse a release marked with a magic `description` field that will make it easier to track latest DCC submissions during the interim period of a quarter.  then, at the very end we can run the normal build and publish steps to prepare that next release and then start over with a new draft...
