### ISSUE TITLE
User_profile record page visible columns and visible foreign keys

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#242]
We decided to use the [user_profile record page in issue #69](https://github.com/nih-cfde/dashboard/issues/69) as the user profile page for CFDE. The visible columns and visible foreign keys annotations should be modified for a better UX.

Include the contents of the my profile popup that are not part of the user_profile table. This includes:
- [x] email
- [x] identities
- [x] groups
 
_pending issue in ermrestjs repo for adding session to templating environment..._
  
- [x] Make visible foreign keys explicit for enabled UX features:
   - saved queries
   - favorite dcc
   - favorite taxon
   - favorite anatomy
   - favorite disease
   - favorite assay type
   - favorite data type
   - favorite file format

**Comment by karlcz** [comment]
The visible foreign keys work is done but the extra profile columns are waiting for a chaise/ermrestjs feature still...

**Comment by karlcz** [comment]
This has been merged and applied to app-dev environment
