### ISSUE TITLE
Portal c2m2 display extensions 2021Q2

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#244]
These model extensions will be mirrored in portal metadata table structures, with the following changes to presentation, search, and export features.

New detailed presentation: all new fields will be exposed when visiting the detail page for one file, biosample, subject, or collection.
- [x] file.compression\_format
- [x] file.bundle\_collection
- [x] biosample.gene
- [x] biosample.substance
- [x] subject.age\_at\_enrollment
- [x] subject.sex
- [x] subject.race
- [x] subject.ethnicity
- [x] subject.substance

Tabular search results presentation will expose some but not all new fields:
- [x] biosample.age\_at\_sampling (theoretically can be an array of ages, but often zero or one?)
- [x] subject.sex
- [x] subject.race
- [x] subject.ethnicity
- [x] subject.age\_at\_enrollment

New search facets:
- [x] collection gene (via biosample\_gene)
- [x] collection substance (via biosample\_substance OR subject\_substance)
- ~collection is-bundle~
- [x] file gene (via biosample\_gene)
- [x] file substance (via biosample\_substance OR subject\_substance)
- [x] file is-bundle
- [x] file compression-format
- [x] biosample gene (via biosample\_gene)
- [x] biosample substances (via biosample\_substance OR subject\_substance)
- [x] biosample subject-age-at-sampling (histogram)
- [x] subject gene (via biosample\_gene)
- [x] subject substance (via biosample\_substance OR subject\_substance)
- [x] subject age-at-enrollment (histogram)
- [x] subject sex
- [x] subject race
- [x] subject ethnicity
- ~subject cause of death~

The search-box allows match on the same gene, substance, gender, race, ethnicity, cause-of-death terms which match by facet (using term id, name, description or synonyms as keywords).

**Comment by karlcz** [comment]
updated checklist for facets/structures visible in empty form.  other fields cannot be verified w/o new test data...

**Comment by karlcz** [comment]
@ACharbonneau  one oddity is that we don't really have a way to show `age_at_sampling` when drilling down on a biosample's detailed record page.  The general case is that it could have multiple subjects and hence multiple ages, even if often times there is only one.

I prototyped showing a list of ages in the compact/tabular view of biosamples (and it just looks like one simple value for the typical case w/ one subject per biosample).  But, once we drill down it might seem funny to show this array decoupled from the listing of subjects we can already show.  However, with the current Chaise UI, I don't think we have a clean way to augment the tabular list of subjects with the age-at-sampling for this particular biosample.

**Comment by karlcz** [comment]
This is just blocked waiting for test data to visually verify things that I think are already implemented in the checklist above. So, I'll just move it to QA lane...

**Comment by ACharbonneau** [comment]
Sorry, I think I don't quite understand what you mean, is there a package in dev I could look at?

**Comment by karlcz** [comment]
I just mean that the last few new items cannot be fully verified until we have synthetic data with full coverage of the new c2m2 features:
- file . compression\_format -> file\_format 
- file . bundle\_collection\_id\_namspace + bundle\_collection\_local\_id -> collection

**Comment by ACharbonneau** [comment]
oh! I'll get that updated asap
