### ISSUE TITLE
Favorites to add 2021Q2

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#245]
In Quarter 1 we merged the favorites feature for anatomy, assay type, and DCC terms. In Quarter 2 we plan on adding disease to this list.

What other favorites should we add? Currently the model includes the following favorites on the `user_profie` table:
 - added already
   - Favorite Anatomy
   - Favorite Assay Type
   - Favorite DCC
 - catch-up of older C2M2 features
   - [x] Favorite Data Type
   - [x] Favorite File Format
   - [x] Favorite Taxon
 - 2021 Q1 C2M2 addition
   - [x] Favorite Disease

Other future changes moved to #249

**Comment by ACharbonneau** [comment]
I think Taxon, Data Type, and File Format would be fine to add. I'm not opposed to the others, but I think I've heard something about subject role and subject granularity being changed in the model. @abradyIGS can you remind me what the deal with those two is and whether it's worth making them options?

**Comment by abradyIGS** [comment]
they're not changing in this quarter's dev model; i don't yet know concretely when, how or in what way they'll change, but in any event, i vote _not_ to include them in the favorites feature for the foreseeable horizon (two quarters' worth of horizon, by my best guess) -- if/when they do change, it will be to make them more straightforward to grok. they're hard enough for DCCs to understand and use, let alone for portal users to configure searches around, so i propose leaving them out of it for the time being.

**Comment by ACharbonneau** [comment]
We are officially doing Taxon, Data Type, and File Format

**Comment by karlcz** [comment]
The checked favorites have been enabled in the app-dev catalog "1" and the app-dev registry's user\_profile detailed view also provides a filtered list of the same favorites (plus saved queries)

**Comment by jrchudy** [comment]
Linking favorites disease issue:
https://github.com/nih-cfde/dashboard/issues/103
