### ISSUE TITLE
Favorites to add to UI 2021Q3

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#249]
Peeling these off of an earlier issue for the 2021Q2 release...

 - 2021 Q2 C2M2 additions to enable in chaise
   - [x] Favorite Gene
   - [x] Favorite Substance
   - [x] Favorite Compound
 - 2021 Q2 C2M2 additions we suspect should **not** be favorited
   - Sex
   - Race
   - Ethnicity

**Comment by jrchudy** [comment]
This should also include changes to the visible foreign keys to display on the user_profile record view.

**Comment by karlcz** [comment]
This is enabled in app-dev but I don't think we have suitable test catalogs, so there isn't much opportunity to test/verify the features yet.
