### ISSUE TITLE
Change column size in datapackage list

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#253]
For the submitted datapackage page, can we make the second column wider?

![image](https://user-images.githubusercontent.com/1719360/137955011-066277a1-d697-496a-b352-a636997b2583.png)

it is getting really long, and when you widen your browser window it just makes the “Status Summary” column wider and wider

![image](https://user-images.githubusercontent.com/1719360/137955037-9b482739-132a-4e68-bb4a-c7a601e15534.png)

**Comment by jrchudy** [comment]
Changes for this have been applied to dev.
