### ISSUE TITLE
Change saved query description column to markdown

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#255]
We briefly discussed changing the description column for the saved_query table from type "text" to type "markdown" so the input and display in deriva would use the markdown formatter/interpreter. 

One downside to making this change would be how we are using the description on the personal dashboard. When user's hover over the name of a saved query, the tooltip includes the name and the description assuming the description is a simple string.
<img src="https://user-images.githubusercontent.com/2932600/137997282-32dc44d0-4619-4046-bf47-f75f2bb100e8.png" height=100 width=300 />

Update: In the Friday UX meeting we discussed
 - removing the description from the tooltip on the personalized dashboard
 - adding a link to the list of saved queries for the user profile page
   - "https://app-dev.nih-cfde.org/chaise/record/#registry/CFDE:user_profile/id=<value>?scrollTo=Saved Query"
 - possibly adding the description column to the table on the personalized dashboard page

**Comment by karlcz** [comment]
The `saved_query`.`description` column in the app-dev registry now has markdown type.
