### ISSUE TITLE
Auto generated search info terminates in semicolon

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#260]
This isn't a blocker, but it makes the names look like they're being artificially truncated:
![image](https://user-images.githubusercontent.com/1719360/139299275-b9ac0e87-c992-411a-8943-08686eee2af4.png)

It would be better if the auto generated text either ended with the last word and no punctuation, or with a period

**Comment by jrchudy** [comment]
This issue is simple to fix and will be focused on during quarter 3 as "Epic 2 technical debt".

**Comment by mschor** [comment]
Hi @jrchudy and @ACharbonneau, I'm trying to tease out what to do here. The ';' is tacked on by Deriva/Chaise, but the truncating and appending of an ellipsis is happening in the dashboard code. For this ticket, I'll remove the truncation completely and we can see how that looks for long-named queries. In terms of the semicolon, it sounds like Josh is going to make that change.

**Comment by ACharbonneau** [comment]
The ellipsis are fine, they're showing real truncation. The semicolons are the weird part

**Comment by jrchudy** [comment]
Saved search default names will no longer have a `;` at the end. This is available on app-dev for testing.
