### ISSUE TITLE
Some facets not appearing/not searchable

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#261]
This round we added compound, substance, gene, sex, race, ethnicity, age at sampling and age at enrollment but it looks like only substance and gene are searchable cross table:

![image](https://user-images.githubusercontent.com/1719360/139449910-18c4906e-b2a7-46cc-94da-04cce70ca50c.png)

~It also doesn't look like they're searchable from the search bar:~ This has been split off to issue #267

**Comment by karlcz** [comment]
This is applied on staging catalog 1
