### ISSUE TITLE
Metadata have inconsistent info tooltips

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#262]
on Subject: Sex, Ethnicity, Project, and Granularity don't have column tooltips, but they do have sidebar tooltips:

![image](https://user-images.githubusercontent.com/1719360/139453342-c9f225aa-37c1-4820-a1bc-65a93c74b330.png)

Same thing for Assay Type, Anatomy and Project in Biosample and Project, File Format, Data Type, and Assay Type on File

**Comment by karlcz** [comment]
these have been added on the staging catalog 1:
- File: Project
- File: File Format
- File: Data Type
- File: Assay Type
- Biosample: Project
- Biosample: Anatomy
- Biosample: Assay Type
- Subject: Project
- Subject: Granularity
- Subject: Sex
- Subject: Ethnicity
