### ISSUE TITLE
Lingering new tab issues

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#263]
This isn't a blocker for release, but is annoying:

- In submitted datapackages, the edit (pencil) opens in a new tab
- in the review page the "Submitted datapackage:" link right under the DCC name opens in a new tab
- The how to guides and feature requests open in the same tab, but shouldn't. They also need link out icons
- Nothing in the nav bar will let me force a new tab (it ignores command + click) all body links let me force a new tab if I want to (which is the correct behavior)

**Comment by jrchudy** [comment]
Addressing each of the 4 above comments:

1. In submitted datapackages, the edit (pencil) opens in a new tab
 - This is the expectation from the "edit" action in the tables in deriva
 - related issue in chaise repo: https://github.com/informatics-isi-edu/chaise/issues/2051

in the dcc_review page in the dashboard repo:
 2. the "Submitted datapackage:" link right under the DCC name opens in a new tab
 3. The how to guides and feature requests open in the same tab, but shouldn't. They also need link out icons

4. Nothing in the nav bar will let me force a new tab (it ignores command + click) all body links let me force a new tab if I want to (which is the correct behavior)
 - i didn't know `cmd + click` was a hotkey for that, will see what deriva can do to fix it
   - `ctrl + click` on windows
 - right click works, and middle click with mouse works

**Comment by jrchudy** [comment]
The changes to the dcc_review page have bene merged into master and will be included in the quarter 2 release.

**Comment by jrchudy** [comment]
The changes for the navbar button click event are in review pending [PR 2151](https://github.com/informatics-isi-edu/chaise/pull/2151) in chaise repo.
