### ISSUE TITLE
Stuck using profile page to edit saved search and not making changes

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#266]
There doesn't seem to be a way to cancel or leave.

https://user-images.githubusercontent.com/1719360/139472945-c74986b4-5951-463a-9746-bdfdcef72416.mov

**Comment by jrchudy** [comment]
This opened in a new tab but amanda didn't realize it when making the video. Going to leave this issue open to discuss during quarter 3 what the expected behavior should be, and how we can fix/mitigate this confusing edit view.
