### ISSUE TITLE
Tooltip for Saved searches when not logged in

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#270]
Is it possible to make the tooltip for unloggedin saved search something like "Log in to save your searches" instead of just a no sign?

![image](https://user-images.githubusercontent.com/1719360/139717620-8ebfe0ad-014e-4675-9090-de2a340cf7be.png)

**Comment by jrchudy** [comment]
Changes for this have been merged and are available on app-dev.
