### ISSUE TITLE
2021Q3 C2M2 presentation changes

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#273]
- [x] Expand c2m2 part 1 extensions into presentation below
- ~Expand c2m2 part 2 extensions into presentation below~

New portal display fields
- [x] `file`.`analysis_type`
- [x] `biosample_disease` qualified by `association_type`
- [x] `subject_disease` qualified by `association_type`
- [x] `collection_disease`
- [x] `subject_phenotype`
- [x] `collection_phenotype`
- [x] `phenotype_gene` association
- [x] `phenotype_disease` association

New registry CV tracking:
- [x] `datapackage_analysis_type` association
- [x] `datapackage_phenotype` association
- [x] `datapackage_disease_association_type` association
- [x] `datapackage_phenotype_association_type` association

New/changed searchbox keyword matching
- [x] analysis type terms
- [x] disease terms (observerd and not-observed)
- [x] phenotype terms (observed and not-observed)

New/changed facets
- [x] Make `disease` facet match any assoc type
- [x] New `phenotype` facet matching any assoc type
- ~New facet for diseases observed?~
- ~New facet for diseases not observed?~
- ~New facet for phenotypes observed?~
- ~New facet for phenotypes not observed?~

**Comment by karlcz** [comment]
A concern regarding disease facets is that we potentially have 6 facets to offer once this quarter's slim maps are integrated:
- any linkage
- any linkage slim-only
- observed
- observed slim-only
- not observed
- not observed slim-only

where the "slim-only" shows a smaller set of choices and the regular form can match on the union of original terms in C2M2 submissions or the slim terms mapped from those original terms.

down the road, I think we need to invent some new UX for this, but in the short term, can we choose a subset of those possible facets to offer?  it seems like the UI will become too cluttered if we start expanding too many of these permutations of association type and/or slim mode.

**Comment by abradyIGS** [comment]
my vote is to only offer the first two, with the intention of aiming the new down-the-road UX at reasonably exposing the observed/not-observed distinction as a search parameter.

**Comment by mgiglio99** [comment]
I agree about just doing the first two for now.
Question - even if it's not a search facet, will users be able to view the relationship type once they have search results now?

**Comment by karlcz** [comment]
Yes, I've prototyped a display to show the association type after the
term name in the relevant places for browsing.  Will need to wait for
extended mock data to fully exercise it though...

**Comment by karlcz** [comment]
However, right now the disease/phenotype displays are ony visible when one navigates all the way down to an individual biosample or subject record, and the detailed associations of that record are shown in its "record" page. We (mostly) only show the C2M2 content of the table itself in that view, i.e. embedded fkeys and scalars.

- Biosample: dcc, project, anatomy, assay type, identifiers, creation time, age at sampling
- Subject: dcc, project, taxonomy, granularity, sex, race, ethnicity, identifiers, creation time, age at enrollment

But it seems we already vioated that for subject.  e.g. taxonomy and race are actually connected via association in C2M2 and not columns of the subject table.

So, do we need to add similar "virtual" columns for disease and phenotype search pages?
