### ISSUE TITLE
2021Q3 C2M2 bag export changes

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#274]
To mirror C2M2 changes made in 2021Q3 release, new/changed export BDBAG elements:
- [x] file analysis type column 
- [x] biosample-disease association type column
- [x] subject-disease association type column
- [x] subject-phenotype association
- [x] collection-disease association
- [x] collection-phenotype association

**Comment by karlcz** [comment]
This is pushed to master and manually tested on a small (unpublished) release catalog.  It was also applied to the existing app-dev published release, but testing there reveals request timeouts when exporting bulk content (w/o filters to reduce the number of files/biosamples in exports).

It needs to be deployed to the AP to affect future app-dev submissions and this version should be included in future release builds.

**Comment by ACharbonneau** [comment]
Does the exporter only export filled tables? I just did an export and am not getting a subject_phenotype, collection_disease or collection_phenotype table at all

**Comment by karlcz** [comment]
yes, I believe the export system omits output CSV files that would have 
zero rows.
