### ISSUE TITLE
Initial mapping of slim terms

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#278]
Need initial mappings for:

- Assay
- Disease
- Data Type
- File Format

So Karl can do initial testing

**Comment by karlcz** [comment]
I assume "File Type" above is meant to refer to the `file_format` vocabulary?

**Comment by karlcz** [comment]
As a further reminder, we need a set of "canonical" terms for _at least_ each slim term ID in a map.  So for each vocab above, we need two TSV files:
- `assay_type_slim.tsv`, `assay_type.tsv`
- `disease_slim.tsv`, `disease.tsv`
- `data_type_slim.tsv`, `data_type.tsv`
- `file_format_slim.tsv`, `file_format.tsv`

that is the slim association (`original_term_id` -> `slim_term_id`) and the normal C2M2 CV format (`id`, `name`, `description`, `synonyms`).

**Comment by karlcz** [comment]
Hmm, it seems those canonical files were already added for these vocabs back in the summer...

**Comment by karlcz** [comment]
These are merged into master and demonstrated on app-dev catalog 1. All the new slim facets seem to work as expected (a smaller list of broad terms) so I think the mechanical testing is done.  I don't know if anyone wants to do further QA to look at the details of the mappings before we call this "initial mapping" issue done?
@ACharbonneau

**Comment by nsuvarnaiari** [comment]
@ACharbonneau 
Can Michelle and I access app-dev to take a look at the slims, just to make sure everything is as expected? 

Thanks,
Suvvi

**Comment by ACharbonneau** [comment]
@nsuvarnaiari @mgiglio99 Sure? It's not access controlled, you just need to go there.
