### ISSUE TITLE
2021Q3 portal model slim map extensions

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#286]
Need portal\_prep table definitions:

- [x] `assay_type_canonical`
- [x] `assay_type_sim_raw`
- [x] `assay_type_slim`
- [x] `assay_type_slim_union`
- [x] `disease_canonical`
- [x] `disease_slim_raw`
- [x] `disease_slim`
- [x] `disease_slim_union`
- [x] `data_type_canonical`
- [x] `data_type_slim_raw`
- [x] `data_type_slim`
- [x] `data_type_slim_union`
- [x] `file_format_canonical`
- [x] `file_format_slim_raw`
- [x] `file_format_slim`
- [x] `file_format_slim_union`

Needed portal\_prep TSV files for anticipated new vocabulary slim maps and canonical term definitions:

- [x] `assay_type_slim.tsv`
- [x] `assay_type.tsv`
- [x] `disease_slim.tsv`
- [x] `disease.tsv`
- [x] `data_type_slim.tsv`
- [x] `data_type.tsv`
- [x] `file_format_slim.tsv`
- [x] `file_format.tsv`

Need portal\_prep ETL definitions

- [x] convert `anatomy.sql` into a reusablel template
- [x] convert `anatomy_slim.sql` into a reusable template
- [x] convert `anatomy_slim_union.sql` into a reusable template

Need portal tables:

- [x] `assay_type_slim`
- [x] `assay_type_slim_union`
- [x] `disease_slim`
- [x] `disease_slim_union`
- [x] `data_type_slim`
- [x] `data_type_slim_union`
- [x] `file_format_slim`
- [x] `file_format_slim_union`

Need facets:

- [x] Assay Type (via slim-union)
- [x] Assay Type (slim only)
- [x] Disease (via slim-union)
- [x] Disease (slim only)
- [x] Data Type (via slim-union)
- [x] Data Type (slim only)
- [x] File Format (via slim-union)
- [x] File Format (slim only)

Change dashboard queries SDK to return slimmed terms

- [x] StatsQuery `assay_type` dimension
- [x] StatsQuery `disease` dimension
- [x] StatsQuery `data_type` dimension
- [x] StatsQuery `file_format` dimension
- [x] StatsQuery2 `assay_type` dimension
- [x] StatsQuery2 `disease` dimension
- [x] StatsQuery2 `data_type` dimension
- [x] StatsQuery2 `file_format` dimension

**Comment by karlcz** [comment]
The first version of this work is complete, but cannot be tested until the new slim maps are committed.

**Comment by mgiglio99** [comment]
Hi Karl - 
We have them all done now, but wanted to give the OWG time to review until the 15th. 
Is that ok? Or should we send you already approved ones (Disease) now?

**Comment by karlcz** [comment]
Could you make a cfde-deriva branch like "slimmaps-2021Q3" and start
committing the TSV files under:

   <repo>/cfde_deriva/configs/portal_prep/<vocab>_slim.tsv

When you branch of latest master, you should see stub files there
already to replace, i.e. they just have the TSV header without any
data rows.

**Comment by mgiglio99** [comment]
Ok - Suvvi will do this.

**Comment by mgiglio99** [comment]
@karlcz - is the 15th ok to have them in - or should we submit what we have now and worry later about OWG review? I think it's unlikely we will get any objection on anything from OWG anyway - so I'm comfortable with submitting now if you want us to.

**Comment by karlcz** [comment]
Putting them in sooner is better to allow other testing of the plumbing.

We can always merge updates to the TSV if you need to regenerate.  We
can just use the same branch, so it is easy to do PRs and see diffs
compared to whatever we've merged so far...
