### ISSUE TITLE
Expose compound cv in faceting and stats

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#290]
Compound is more general/abstract than substance and more relevant for search UX

- [ ] Add compound to core-fact breakown
- [ ] Add compound to level1-stats
- [ ] Add compound facets
- [ ] Enable compound favorites
- [ ] Hide substance facets?
- Should substance be enabled for favoriting too?

@abradyIGS  @ACharbonneau

**Comment by ACharbonneau** [comment]
Substance won't be favoriteable. If it helps with UI real estate I think we could hide the facet too and just make it searchable via the search box

**Comment by karlcz** [comment]
Is this a Q3 blocker?  It is linked from the Q3 ingest issue but this issue itself isn't listed in Q3.  I'm wondering if we can consider this tech debt to work on later or need to rush it now...

**Comment by ACharbonneau** [comment]
Sorry, is what a Q3 blocker?

**Comment by karlcz** [comment]
Reprhasing: is the "compound" (rather than "substance") facet and
stats dimension a blocker for the upcoming release or something we can
improve in the next cycle?

In the current dev code, we have "substance" exposed as a facet and
"compound" would only be found indirectly by navigating to a substance
page.

**Comment by ACharbonneau** [comment]
The thing we care about is "compound". If we only have substance for Q3 I guess that's fine, but we should swap them for Q4 and only show compound.

**Comment by karlcz** [comment]
A change is merged and deployed on app-dev to include the Compound facet.  For now, the existing Substance facet is still there, but we can easily hide that for the upcoming release, if preferred.

**Comment by ACharbonneau** [comment]
filtering by substance seems to make the compound filter hang
![image](https://user-images.githubusercontent.com/1719360/151598030-f61ab987-dfe5-46d9-a89a-fca13cc7fa4c.png)

**Comment by ACharbonneau** [comment]
heh. and then it crashes the site:

![image](https://user-images.githubusercontent.com/1719360/151598172-161e9e52-751d-4a1d-8b07-12c6a0606e1b.png)

put me back at the home page when I said ok

**Comment by karlcz** [comment]
I think this is current designed UX for Chaise. Clicking "Close" would 
have left you in the app with broken results section and let you amend 
the query terms.
