### ISSUE TITLE
Admin tool to prune favorites orphaned by release catalog

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#292]
To simplify the UX for naive users, there is a desire to purge favorites for all users when the new relelase has orphaned terms.
This will be a partial mitigation for #259  at release boundaries.

**Comment by karlcz** [comment]
This tool is implemented as a new `python -m cfde_deriva.release prune-favorites` _release id_ CLI subcommand.

It has been run against app-dev to remove orphaned favorites relative to the current app-dev release catalog on 2022-01-10.

**Comment by ACharbonneau** [comment]
I have no idea how to test this
