### ISSUE TITLE
Test bag export scenarios needed for workshop

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#293]
~The export configurations were written prior to quarter 3. Since then, some model changes have occurred and the export configurations need to be retested with the mock data from staging to verify no regressions were created.~

This issue was left open and is probably significant again...  we should be sure to test export scenarios that will be relevant to the upcoming workshop in ~April~ May (?) as part of the QA cycle.  Things to be concerned about:

- changes to the handling of timeouts and concurrency limits in the export service layer
- the new q4 extensions to c2m2 (protein CV, many new collection<->CV associations)
- more revisions to the portal fact/warehouse structures which affect query performance and therefore which export scenarios are feasible within the current synchronous export API

**Comment by karlcz** [comment]
Here is one query described by Michelle and Suvvi:

- File Format:FASTQ
- Assay Type: exome sequencing assay, RNA-seq assay
- Common Fund Program: HMP: The Human Microbiome Project

with the latest HMP submission, this matches approximately 1400 files.
