### ISSUE TITLE
Remove substance as a favorite

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#294]
At the beginning of quarter 3, we discussed adding compound, gene, and substance as favorites. Since then, we've decided that having favorite substances is not needed. 

It looks like the plumbing for favorite substances is in the model (allowing for a favorite from the facet and showing related table in record app of the favorite substances) and should be removed to prevent any confusion in the UX.

**Comment by ACharbonneau** [comment]
did this get done?

**Comment by karlcz** [comment]
I believe we turned off the favorites star mechanism for substance in the portal and hid it in the user profile page in Chaise, but I do not know whether the personal dashboard has any related work.

**Comment by jrchudy** [comment]
There is no favorite substance widget visible on the personal dashboard, closing this issue.
