### ISSUE TITLE
Hide substance facet

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#307]
The substance and compound facets time out when you use the other. Let's just hide substance so users only can interact with compound.

**Comment by karlcz** [comment]
This has been applied to the staging catalog 1, and the existing review catalogs in staging should be reconfigured shortly.

**Comment by ACharbonneau** [comment]
Did this get finished for the release?

**Comment by karlcz** [comment]
Yes, substance facets got dropped from the core 
file/biosample/subject/collection table searches. It remains as a facet 
if one is digging around in the compound vocabulary itself.

**Comment by ACharbonneau** [comment]
kk
