### ISSUE TITLE
2021Q4 RAS dbgap profile info

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#311]
- [x] webauthn integration with Globus RAS attribute provider info source
- [x] appropriate configuration of webauthn for session lifecycle with RAS attributes (maximum login session duration?)
- [x] CFDE user profile page RAS attribute presentation

**Comment by lliming** [comment]
Laura Pearlman (ISI) is working to set up a development environment to do this. @lliming gave her details on how to configure the Globus SDK (or anything, really) to run against Globus's Preview environment, where the RAS feature is available for development. Globus Preview is running against RAS Staging.

**Comment by karlcz** [comment]
This is pending some deployment/integration issues as we switched to a plan to access the testing/staging RAS login provider as part of the _production_ Globus login services.

As soon as we can test/verify the integration in the app-dev environment, we will add it to the app-staging release candidate.

**Comment by karlcz** [comment]
This is now in place in both app-dev and app-staging. At the moment, one must login with the "NIH RAS (staging)" identity provider using one of the RAS sandbox test accounts in order to see any dgGaP permissions.  All others will see _not supported by login method_ in their user profile for the dbGaP Permissions field.

Eventually, when agreements are executed, we expect the "eRA Commons" identity provider to start showing dbGaP permission values for real user accounts. The portal feature is intended to work transparently with that, but we should plan to test and (as needed) adjust the production deployment if any new interop issues are found.
