### ISSUE TITLE
Potential Personal Collection Updates

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#315]
OK. I have poked this and it seems like the basic functionality is working. I have a few comments for things we should improve either now or in coming quarters, depending on difficulty:

- For files without persistent ids, it doesn't let me add them, but doesn't give any indication why. I think hover text on the greyed out button would be good
- we need quite a lot of documentation to make this make sense to someone, I think @fridayek might want to start figuring this out from dev rather than waiting
- There should be a widget in the dashboard of my personal collections that functions much like the saved searches, it is super not obvious how to get to personal collections otherwise
- It would be good if the filter panel was open by default when I click "add record" when on my personal collection page to do a bulk add. it's very not obvious that you can filter from there

_Originally posted by @ACharbonneau in https://github.com/nih-cfde/cfde-deriva/issues/268#issuecomment-996209746_

**Comment by jrchudy** [comment]
Closing this issue since the above bullet points have been addressed in other issues in cfde-deriva and dashboard repos.
