### ISSUE TITLE
Documentation for CLI tool

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#319]
Not sure if Mike is writing this documentation, or if @fridayek is. My team could probably help after using it at the hackathon cc: @nih-cfde/training

**Comment by RLC-DCPPC** [comment]
@mikedarcy , how about this? If there is a tool there should be instructions.

**Comment by mikedarcy** [comment]
This has been superseded by the implementation in described in https://github.com/nih-cfde/cfde-deriva/issues/334.
