### ISSUE TITLE
Review and fix markdown table usage in templates

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#320]
It seems like some/many of our markdown tables used for "card views" are broken on app-dev with recent Chaise and ermrestjs updates.  See for example https://app-dev.nih-cfde.org/chaise/recordset/#registry/CFDE:release  but there may be more occurrences...

We should search the registry and portal schema JSON files for the `|` character used in markdown tables and test/review each template on app-dev.

**Comment by karlcz** [comment]
This is fixed in app-dev.  There are only 4 occurrences of markdown tables in the registry config, seen in the submission and release listings (2 cards each).

**Comment by jrchudy** [comment]
The change we made in ermrestJS for markdown table formatting only applies when an attribute block is provided after the table template. For instance, if the markdown template looked something like: `| ... | \n {.class-name attribute=value}`

Then it would have to be changed to include a 2nd `\n` to be defined like: `| ... | \n\n {.class-name attribute=value}`.

In the places that a markdown template is used to create a table like display, this attribute block is not being used, so no changes are needed.
