### ISSUE TITLE
Taxonomy sidebar naming

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#341]
One of these is a slim, but both boxes have the same name. please update the slim one

![image](https://user-images.githubusercontent.com/1719360/160695051-b8b03856-9c35-40e6-9c8d-804dae10d7d7.png)

**Comment by karlcz** [comment]
This is fixed in the release catalogs on dev and staging.  I will also reconfigure the constituent review catalogs of those releases, but other submissions will retain the older facet names.  Once this fix is deployed the action providers, new submissions will also get the revised name.
