### ISSUE TITLE
CV term related entities should show related collections

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#342]
Because C2M2 gained many connections between collections and CV terms, we should show related collections when looking at a detail page for one CV term.

These direct associations exist in the latest C2M2:
- `collection_disease`
- `collection_phenotype`
- `collection_gene`
- `collection_compound`
- `collection_substance`
- `collection_taxonomy`
- `collection_anatomy`
- `collection_protein`

**Comment by karlcz** [comment]
This is ready to test on the app-staging release catalog  (catalog 1)

**Comment by ACharbonneau** [comment]
looks good to me! There's a couple that are a little weird because they show up in the facet but then aren't directly connected to a collection, but I think it will be fine once DCCs actually submit with the new collection tables and can make the direct links
