### ISSUE TITLE
Hide column name on vocabulary term pages for markdown display

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#352]
There is markdown content on some vocabulary record pages where the `entity-key` column is being shown which creates a lot of whitespace. @abradyIGS mentioned this display will show on gene, anatomy, and some other vocabulary pages.

Example on a production gene page:
https://app.nih-cfde.org/chaise/record/#1/CFDE:gene/nid=1

**Comment by abradyIGS** [comment]
genes, anatomy, disease and compound. (see also https://github.com/nih-cfde/deliverables/issues/401)

**Comment by karlcz** [comment]
This has been merged and applied to the current app-dev release catalog "1" where you can see the changed layout.  Once we get this deployed to the dev action provider, subsequent submissions will also get the change in their new review catalogs.

**Comment by karlcz** [comment]
This one was already released to prod. We just forgot to update the QA confirmation here.
