### ISSUE TITLE
update the portal navbar menu for docs, help, and contacting CFDE

### ISSUE THREAD

**Issue by jeremywalter** [nih-cfde/cfde-deriva#364]
## Summary

Several changes to the portal navbar lifted from conversation below:

- [x] make “Contact the Helpdesk” to be the first link under the “User Help” panel and keep the rest of the links in the same order
- [x] change the text of the "Cohort Building Tutorials" link to "Tutorials"
- [x] make sure the link will open an email client to [support@cfde.atlassian.net](mailto:support@cfde.atlassian.net)
- [x] fix a bug in the Chaise front-end that is interfering with the `mailto:` links

## Original issue text

The 'e-mail the helpdesk' link is broken on the portal page:

While it is being fixed I think it would be nice to change it to 'Contact the Helpdesk' and move it to the top of bottom of the options to feature it... this would bring it in line more with the language on all our other sites (Contact Us, or Contact) and make it more visible to users.

Actual contact detail should still be: support@cfde.atlassian.net

![image](https://user-images.githubusercontent.com/40613731/175363420-84461f52-d431-460d-826a-f84ce1236f79.png)

**Comment by raynamharris** [comment]
Also, note that not only the name need to be changed, but we need to make sure the email works. Something about it is registering as unsafe.

After clicking "email the help desk" is says "about:blank" or "unsafe:mailto:support@cfde.atlassian.net" instead of opening an email client.

**Comment by raynamharris** [comment]
the email is correct

**Comment by jessicalumian** [comment]
We would like the following changes:

- make “Contact the Helpdesk” to be the first link under the “User Help” panel and keep the rest of the links in the same order
- make sure the link will open an email client to [support@cfde.atlassian.net](mailto:support@cfde.atlassian.net)
- change the text of the "Cohort Building Tutorials" link to "Tutorials"

thank you!

**Comment by karlcz** [comment]
All the parts were integrated in prior releases.
