### ISSUE TITLE
File table displays do not include dbGaP indicators when user has no dbGaP permissions

### ISSUE THREAD

**Issue by lliming** [nih-cfde/cfde-deriva#375]
When I login to the CFDE portal using NIH's RAS service, but I don't have any dbGaP permissions, the portal doesn't display any colorful indicators indicating that a file requires permission, and I don't have that permission. It instead behaves as though I didn't login with RAS and it doesn't know my permissions.

**Comment by karlcz** [comment]
A fix for this regression has been applied to the dev and staging servers.  It is committed in the cfde-deriva and will be included in any future releases.

It could be applied to production for the public catalog as an interim fix, if desired, before the next general portal release.

**Comment by karlcz** [comment]
This was applied to production as described above and included for future releases too.
