### ISSUE TITLE
Operational error when a submission introduces a new dbgap study id

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#381]
When a test submission included a dbgap study ID not known by the built-in table of IDs, the ingest process encountered a 403 forbidden error when attempting to insert the new study ID into the registry's dbgap study ID table.

**Comment by karlcz** [comment]
@raynamharris  We noticed these 'operational error' submissions you made recently, and this seems to be the explanation from the logs. We're testing a registry access control policy fix to solve this.

But, I wonder if you're using a real dbgap study ID that our system doesn't know about, or some other mock/synthetic value in these recent mock submissions?

**Comment by raynamharris** [comment]
mine were mock dbgap study IDs. they were made by pasting "ras:phs" to a random number.
