### ISSUE TITLE
Remove schema assumptions in CfdeDataPackage

### ISSUE THREAD

**Issue by jgaff** [nih-cfde/cfde-deriva#4]
There are some assumptions about the schema of data being loaded into DERIVA, in the `CfdeDataPackage`, found specifically in the `provision_denorm_tables` method (e.g. column `method` must exist in table `DataEvent` in [this code](https://github.com/nih-cfde/cfde-deriva/blob/master/cfde_deriva/datapackage.py#L169). These assumptions break the goal of this tool being generally C2M2-version agnostic, and are causing otherwise-valid data to fail to load into DERIVA.

The `CfdeDataPackage` should be modified to not require these columns in order to load data into DERIVA, so the tool doesn't need to be updated as the C2M2 changes.

**Comment by ACharbonneau** [comment]
ingest. superceded by model change
