### ISSUE TITLE
Authorization model

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#56]
may affect data model (level 1? or higher?)

could survey models from DCCs

dbGaP

Phenotype driven [use case](https://cfde-usecases.readthedocs-hosted.com/en/latest/use-cases/uc0005-researcher-browse-and-filter-complex/) to build on. <link here>

combinations may need to be made private (de-identified)  to protect privacy.

**Comment by ACharbonneau** [comment]
align planning IAM
