### ISSUE TITLE
Infrastructure Planning Doc

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#64]
Draft a one-page document to cover design and organizational issues for the Infrastructure focus area.

**Comment by ACharbonneau** [comment]
https://docs.google.com/document/d/1au899t1ZEQqZzOInMnaSyba0ZKYOKLaD-NWWErrXg6w/edit?usp=sharing

**Comment by ACharbonneau** [comment]
From https://github.com/nih-cfde/cfde-deriva/issues/44


[system diagram](https://docs.google.com/presentation/d/1FJRSSkx3p8wpXoS8dmVr4FezLIa7YdUohWaOvPQVVGg/edit#slide=id.g7e218382c9_0_7)

waiting for STRIDES AWS accounts, but in the meantime

standup a VPC? need dedicated one for CFDE production deployment

UMB to set up local copy using our AWS account, Mike can provide access through firewall rules.

VPC environments? staging, devel, prod. Owned by STRIDES account

Need GLOBUS auth

- [ ] level 0 and level 1 C2M2 model
- [ ] ingested into Deriva catalog
- [ ] need a stable version of the catalog that HMP should be loaded into Deriva (need to loop in @jgaff )

- [ ] - Set up proxies
- [ ] - reserve words for Deriva SPI endpoints
- [ ] - security/auth for dashboard
- [ ] - depends on REST API between dashboards and Deriva
