### ISSUE TITLE
API Planning Doc

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#65]
Draft a one-page document to cover design and organizational issues for the API focus area.

**Comment by RLC-DCPPC** [comment]
draft is [here](https://docs.google.com/document/d/1I4GC6mBXRwCGOs12ANDMD3N1YFueqkTtRjRuacAdxx0/edit).

**Comment by abradyIGS** [comment]
document is set and [stable](https://docs.google.com/document/d/1zOAAkGnFHRZ6M07Jrt9dnU2bvmxlWRrdf2Bwi62T6DA); closing issue

**Comment by ACharbonneau** [comment]
yep. please be sure an estimate is set on issues first, but I'm pro-human-who-did-the-thing closing the issue

**Comment by abradyIGS** [comment]
okay. i set the estimate to [an arbitrary] "5" [because i haven't evolved a frame of reference yet]; closing.
