### ISSUE TITLE
Improve Documentation for Public Beta Release

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#68]
We are scheduled to release the portal to the public 9/30/20. These are the docs that should be available by then.

**Comment by RLC-DCPPC** [comment]
Hi @fridayek, this is the closest I could find for a ticket related to the user guide. Sounds like this one should also have a documentation tag (done). But, maybe this should also have sub-issues if there are docs other than the user guide for the recent release.

**Comment by ACharbonneau** [comment]
They're attached to the Authenticated self-service data ingest by DCCs epic: https://github.com/nih-cfde/planning-docs/issues/73

**Comment by ACharbonneau** [comment]
This was done/should have been closed in october
