### ISSUE TITLE
Deploy Ingest AP into production VPC

### ISSUE THREAD

**Issue by victor73** [nih-cfde/cfde-deriva#79]

**Comment by victor73** [comment]
Added to Epic 1. Wasn't assigned for some reason.

**Comment by jgaff** [comment]
I thought the deployment tasks were being tracked in the systems infrastructure repo? The ingest AP is already deployed into the Prod VPC: https://github.com/nih-cfde/systems-infrastructure/issues/1

**Comment by victor73** [comment]
Yeah, not sure what happened. May have been filed in the wrong repo and inadvertently duplicated.
