### ISSUE TITLE
Enhance dashboard queries for Epic 1

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#81]
Revise or extend the dashboard queries module to support additional measures needed for the Epic 1 use case.

The branch and PR #95 will collect discussion and changes related to this issue.

## Sub-tasks

- [x] Document existing
- [x] Gap analysis
- [x] Draft spec of feature changes
- [x] Modify code
- [ ] Test new features
- [ ] Merge PR

## Summary of gaps

- Restrict results to one DCC.
- ~Allow vocabulary dimensions as a base entity instead, to get basic counts of terms used by project.~
- Allow subproject drill-down to get more detailed rollups besides the top-level DCC root project rollups.

At last meeting, it was suggested that we do not need to use vocabulary dimensions as base entity in this cycle. Just returning the results grouped by vocabulary may continue to suffice.

## Summary of changes

- Add support for `.dimension("subproject", parent_project_RID=rid)`
- Modify `list_projects()` method to complement new subproject dimension feature
- Adjust for C2M2 changes (mostly `local_id` column naming and relocation of `assay_type` foreign key to file table)

**Comment by karlcz** [comment]
The current dashboard queries module focuses on counting/summarizing a choice of 3 base entity types:
- file
- biosample
- subject

The other vocabulary term tables and project table are brought in as dimensions for grouped statistics, but cannot currently themelves be counted:

- anatomy
- assay\_type
- data\_type
- species (subset of ncbi\_taxonomy)
- project\_root (top-level subset of project)

**Comment by karlcz** [comment]
This punch-list is drawn from the Epic 1 description and organized by coverage.

## Mostly covered by existing query module

- How many data files exist for my DCC overall
- How many subjects are represented

Existing stats can be grouped by the `project_root` dimension which corresponds to DCC. However, there is no option to limit the results to only one root project, so other unnecessary stats are also returned.

## Not covered as countable entities

- How many and which data types are represented
- How many and which anatomy terms are represented

These are currently exposed as grouping dimensions, but not base countable entities.  If we add them as entities, how much can/should we limit the other grouping dimension aspects of the query module?  Can we assume that the project attribution should be the _most closely connected_ entity, i.e. data types are found for the file's project and anatomy are found by the biosample's project?

## Needs clarification

-  A list of Project names
-  Number of biosamples in that Project
-  Number of data\_type in that Project

It seems to me that this repeats the preceding goals but with a desire to drill down below the DCC `project_root` level of the model for attribution.  But how far should it drill down?  Is it the next level of projects listed as members of the root project? Or the most specific project actually attributed by the relevant C2M2 entity records?

@ACharbonneau   @abradyIGS

**Comment by ACharbonneau** [comment]
I'm not sure if this is the right place to put it, but I've made a first draft of a walkthrough/wireframe for the report page: https://docs.google.com/presentation/d/1ZOu4S6Y5C8BvIH9iSUaui6SHutN1frIMjh28ESznNQE/edit#slide=id.p
