### ISSUE TITLE
Table of each person associated with DCCs by globus group

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#84]
Text from [EPIC 1 statement](https://docs.google.com/document/d/1WV9Y2KR-tTXQlHxq7fDQztHvuK3DuLwh89-zVLi3JmY/edit?disco=AAAAKNa5V5U):
> As a DCC PI, I want to go to the CFDE portal and see a personalized dashboard interface where I can verify the data > currently available for my DCC. 
>   - “Personalized” Login options
>      - Registration + a record table of who is from which DCC

Users want to be able to register for specific DCCs to see a dashboard for that DCC. Group creation and registration is managed in this [related issue](https://github.com/nih-cfde/training-and-engagement/issues/176). Once groups are created, make visible a table of who is from which DCC based on globus group membership.

**Comment by ACharbonneau** [comment]
Is this the table you need? https://github.com/nih-cfde/training-and-engagement/issues/176#issuecomment-693535998

**Comment by jrchudy** [comment]
Thank you. This is the unique set of group names that each user could have. The table mentioned in this issue would be to include a "Person" table that would have information on each user in the system potentially connected to one of these groups.

**Comment by lliming** [comment]
Is it actually a requirement that we "make visible a table of who is from which DCC based on globus group membership?"  What purpose does this serve for the portal user?

**Comment by karlcz** [comment]
I echo Lee's question above.  But, FWIW, the submission registry will have a prerequisite aspect of this: a listing of onboarded DCCs and a listing of which groups have what role with respect to a DCC.  E.g. "group X is for data-submitters for DCC Y".  However, it is not currently planned to have a list of users in each group.

**Comment by jrchudy** [comment]
I don't think this is a requirement that we decided to include. This was mentioned in the EPIC 1 statement, but was never brought up as a necessity for PIs in any of the DCCs.

**Comment by karlcz** [comment]
Closing this as won't fix...
