### ISSUE TITLE
Personalized Dashboard for PIs in a DCC

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#85]
PIs for DCCs want to be able to go to the CFDE portal and see a personalized dashboard interface where data for the current DCC can be verified.

**Comment by RLC-DCPPC** [comment]
Is there more to do here? Testing, perhaps? (It's indirectly blocking Epic 2)

**Comment by jrchudy** [comment]
Seems like each of the underlying issues were closed. If there's more to do with this epic, we can open issues to "fix" those problems and attach them to the "Epic 2 technical debt" epic.
