### ISSUE TITLE
List of project names with extra information

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#86]
The dashboard should include a list of Project names with some queried sets of data. For example:
 - Number of biosamples in that Project
 - Number of data_type in that Project

**Comment by karlcz** [comment]
Is this just extra summary info we would like to see on the regular project listings?

**Comment by jrchudy** [comment]
This was opened as part of EPIC 1 after digesting the EPIC 1 statement. Looks like the contents of this issue were directed at the dashboard and dcc review page. Both of those pages show "queried set of data".
