### ISSUE TITLE
Portal - Cia process

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#9]
Start: 1/1/20
End: 4/1/20

work with Cia Romano:  do user interviews and develop user preferences for the CFDE Portal.

**Comment by RLC-DCPPC** [comment]
Hi @kutkatl. Okay to move this to the right (4/1-11/1) in line with Cia's contract with Carl?

**Comment by kutkatl** [comment]
Yes, again sorry for the delay.
