### ISSUE TITLE
Update C2M2 Level 1 JSON Schema

### ISSUE THREAD

**Issue by abradyIGS** [nih-cfde/cfde-deriva#92]
cf. §4.1 [here](https://docs.google.com/document/d/1-Ef1iW772QFo_XScoxlH1NU91kpH3Vcgeazss-EMP-c)

**Comment by swandle06** [comment]
@abradyIGS With regard to this note from section 1.1 of the Google Doc referenced above:
the C2M2 biosample entity
- assay_type will be moved from biosample to file.
- anatomy will stay where it is (attached to biosample).

@dcfcjcheadle and I ran across this while working on the following issue: https://github.com/nih-cfde/the-fair-cookbook/issues/43. In our case, there were multiple assay_types per file as well as multiple assay_types per biosample. The duplicates with respect to file were minimal compared to the duplicates with respect to biosample, so the file duplicates could be the result of an error in the input data. In thinking a little more about it, however, we were able to come up with several scenarios where multiple assay_types could be in a single file. The most obvious example would be a tab-delimited file containing phenotype data with a different assay type in each column, but I can also imagine more complicated scenarios such as an RNA-Seq and WGS run on a single lane of a high-throughput sequencer when using sample multiplexing. The latter is one possibility for the example we found if it isn't a labeling error.

Have you encountered this before? Have you considered connecting assay type to both biosample and file via association tables as you've done for file and biosample?

**Comment by abradyIGS** [comment]
@swandle06 @dcfcjcheadle 

(sorry for my delay in replying and also for closing this issue prematurely; i'm still groping my way blindly around zenhub with mixed success)

regarding multiplicity: requiring exactly zero or one attributions of this sort (e.g. assay_type) is one of the many ugly compromises we've decided to stick with for C2M2 Level 1, in an ongoing effort to minimize complexity, both for C2M2 metadata builders and for the querying app layer.

C2M2 Level 2 (a full draft of which is slated to be published by end of 2020) is definitely going to expand this "one field" approximation into an arbitrary-multiplicity association relationship, so data custodians will be able to attach as many values as they like for each of the CV-controlled decorators.

(Level 2 is the "fully mature information interchange" version of C2M2 wherein we do our best to capture every last morsel of DCC metadata: Level 1 is the "everyone might hate it but it's easy to harmonize across datasets for searches and other useful aggregating functions" compromise that lives between Level 2 and the "plain old list of files" that is Level 0.)

For now, the guidance (usage guidance is being updated now, for draft publication in the next couple of weeks) is just "select whichever value seems to be the most appropriate one and use that, ignoring all others. If that ends up looking unacceptably misleading, feel free to leave it null for the purposes of Level 1 serialization."

**Comment by abradyIGS** [comment]
updated JSON (stay tuned, i'm about to update it again) is [here](https://github.com/nih-cfde/specifications-and-documentation/blob/master/draft-C2M2_JSON_Schema_datapackage_specs/C2M2_Level_1.datapackage.json)
