### ISSUE TITLE
Onboarding instructions for DCC reviewers for Epic 1

### ISSUE THREAD

**Issue by lliming** [nih-cfde/cfde-deriva#94]

**Comment by lliming** [comment]
I did not mean to create this issue in the cfde-deriva repo. :( It happened automatically when I created a new issue for Epic 1 in ZenHub and it didn't ask me which repo to put the issue in. I will create the issue in the correct repo. Sorry for the noise.

**Comment by ACharbonneau** [comment]
@lliming Just FYI, you can move issues across repos, so if you make it in the wrong spot, it's an easy fix. If you're on github there's a 'transfer issue' link on the bottom right of the issue page
