### ISSUE TITLE
Build dev catalog with epic1 content

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#96]
- Hand-load revised datapackages to individually test C2M2 updates.
   - [x] HMP
   - [x] LINCS
   - [x] 4DN
   - [x] Metabolomics
   - [x] KidsFirst
   - [x] GTEX
   - [x] Motrpac
- [x] Hand-load revised datapackages for integrated testing
- [x] Revise and test post-load ETL scripts to support Chaise portal etc.
- [x] Announce dev catalog when ready for dev consumers

**Comment by karlcz** [comment]
HMP data is loaded in dev environment on app-dev catalog 6.

**Comment by karlcz** [comment]
4DN, LINCS, and Metabolomics are loaded on app-dev in catalogs 9, 10, 11, respectively.

A draft combined-load of HMP, 4DN, LINCS, and Metabolomics is in catalog 12.

**Comment by RLC-DCPPC** [comment]
@rpwagner is working on GTEX and Motrpac, hoping to be done today.

**Comment by karlcz** [comment]
GTEX and Motrpac are loaded in app-dev catalogs 22 and 23, respectively.

**Comment by karlcz** [comment]
The merged app-dev catalog 21 has been expanded with GTEX and Motrpac content.
